#!/bin/bash
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/mnt/shared-storage-user/puyuan/code/OpenClaw-RL}"
RUNS_ROOT="${RUNS_ROOT:-${REPO_ROOT}/runs}"
if [[ -n "${RUN_DIR:-}" ]]; then
    DEFAULT_REMOTE_LOG_ROOT="${RUN_DIR}/remote_logs"
elif [[ -n "${RUN_ID:-}" ]]; then
    DEFAULT_REMOTE_LOG_ROOT="${RUNS_ROOT}/${RUN_ID}/remote_logs"
else
    DEFAULT_REMOTE_LOG_ROOT="${RUNS_ROOT}/remote_logs"
fi
REMOTE_LOG_ROOT="${REMOTE_LOG_ROOT:-${DEFAULT_REMOTE_LOG_ROOT}}"
CPU_WORKER_ID="${CPU_WORKER_ID:-$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo unknown-worker)}"
CPU_WORKER_ID="$(printf '%s' "${CPU_WORKER_ID}" | tr -c 'A-Za-z0-9_.-' '_')"
OPENCLAW_REMOTE_RUN_ID="${OPENCLAW_REMOTE_RUN_ID:-$(date +%Y%m%d_%H%M%S)_pid$$}"
OPENCLAW_REMOTE_LOG_DIR="${OPENCLAW_REMOTE_LOG_DIR:-${REMOTE_LOG_ROOT}/${CPU_WORKER_ID}/${OPENCLAW_REMOTE_RUN_ID}}"
export REPO_ROOT RUNS_ROOT REMOTE_LOG_ROOT CPU_WORKER_ID OPENCLAW_REMOTE_RUN_ID OPENCLAW_REMOTE_LOG_DIR
export LOG_FILE="${LOG_FILE:-${OPENCLAW_REMOTE_LOG_DIR}/docker_watchdog.log}"
export POOL_HOST="${POOL_HOST:-127.0.0.1}"
export POOL_PORT="${POOL_PORT:-18081}"
export POOL_CHECK_INTERVAL="${POOL_CHECK_INTERVAL:-30}"
export POOL_PENDING_CLOSES_WARN="${POOL_PENDING_CLOSES_WARN:-50}"
export POOL_PENDING_CLOSES_REPAIR="${POOL_PENDING_CLOSES_REPAIR:-1}"
export POOL_PENDING_CLOSES_REPAIR_THRESHOLD="${POOL_PENDING_CLOSES_REPAIR_THRESHOLD:-50}"
export POOL_PENDING_CLOSES_STUCK_CHECKS="${POOL_PENDING_CLOSES_STUCK_CHECKS:-2}"
export POOL_PENDING_CLOSES_ACTIVE_MAX="${POOL_PENDING_CLOSES_ACTIVE_MAX:--1}"
export POOL_PENDING_CLOSES_REAP_LIMIT="${POOL_PENDING_CLOSES_REAP_LIMIT:-0}"
export POOL_PENDING_CLOSES_REPAIR_COOLDOWN_S="${POOL_PENDING_CLOSES_REPAIR_COOLDOWN_S:-120}"
export POOL_PENDING_CLOSES_CANCEL_API="${POOL_PENDING_CLOSES_CANCEL_API:-1}"
export POOL_PENDING_CLOSES_CANCEL_TIMEOUT="${POOL_PENDING_CLOSES_CANCEL_TIMEOUT:-5}"
export POOL_PENDING_CLOSES_CANCEL_MIN_AGE="${POOL_PENDING_CLOSES_CANCEL_MIN_AGE:-45}"
export POOL_READY_FAILS_RESTART="${POOL_READY_FAILS_RESTART:-6}"
export POOL_RESTART_ACTIVE_MAX="${POOL_RESTART_ACTIVE_MAX:-0}"
export POOL_RESTART_COOLDOWN_S="${POOL_RESTART_COOLDOWN_S:-300}"
export WATCHDOG_STOP_POOL_LAUNCHER="${WATCHDOG_STOP_POOL_LAUNCHER:-0}"
export POOL_E2E_PROBE_INTERVAL="${POOL_E2E_PROBE_INTERVAL:-0}"
export POOL_E2E_PROBE_PAYLOAD_FILE="${POOL_E2E_PROBE_PAYLOAD_FILE:-}"
export POOL_E2E_PROBE_TIMEOUT="${POOL_E2E_PROBE_TIMEOUT:-600}"
export POOL_E2E_PROBE_FAILS_RESTART="${POOL_E2E_PROBE_FAILS_RESTART:-2}"
export POOL_RESET_STORM_REPAIR="${POOL_RESET_STORM_REPAIR:-1}"
export POOL_RESET_STORM_MIN_RESETTING="${POOL_RESET_STORM_MIN_RESETTING:-32}"
export POOL_RESET_STORM_RATIO_PCT="${POOL_RESET_STORM_RATIO_PCT:-80}"
export POOL_RESET_STORM_MIN_AGE="${POOL_RESET_STORM_MIN_AGE:-390}"
export POOL_RESET_STORM_STUCK_CHECKS="${POOL_RESET_STORM_STUCK_CHECKS:-2}"
export POOL_RESET_STORM_REPAIR_LIMIT="${POOL_RESET_STORM_REPAIR_LIMIT:-64}"
export POOL_RESET_STORM_REPAIR_COOLDOWN_S="${POOL_RESET_STORM_REPAIR_COOLDOWN_S:-120}"
export MAX_RUNNING_CONTAINERS="${MAX_RUNNING_CONTAINERS:-80}"
export HARD_KILL_THRESHOLD="${HARD_KILL_THRESHOLD:-128}"
export PIDS_WARN_PCT="${PIDS_WARN_PCT:-55}"
export PIDS_EMERGENCY_PCT="${PIDS_EMERGENCY_PCT:-70}"
export PIDS_EMERGENCY_MIN_FREE="${PIDS_EMERGENCY_MIN_FREE:-3500}"
export TASK_CONTAINER_REGEX='^[0-9]+[-_].*(slime[-_]?run|client|helper).*$'
export TASK_IMAGE_REGEX='^tb__[0-9]+__.*(:|$)'
export WATCHDOG_AGGRESSIVE_IMAGE_PRUNE="${WATCHDOG_AGGRESSIVE_IMAGE_PRUNE:-0}"
export WATCHDOG_DOCKER_STORAGE_GC="${WATCHDOG_DOCKER_STORAGE_GC:-1}"
export DOCKER_GC_TRIGGER_USED_PCT="${DOCKER_GC_TRIGGER_USED_PCT:-85}"
export DOCKER_GC_TARGET_USED_PCT="${DOCKER_GC_TARGET_USED_PCT:-70}"
export DOCKER_GC_MIN_FREE_GB="${DOCKER_GC_MIN_FREE_GB:-${DISK_MIN_FREE_GB:-20}}"
export DOCKER_GC_KEEP_PATTERNS="${DOCKER_GC_KEEP_PATTERNS:-ghcr.io/laude-institute/t-bench/*,ubuntu:*,python:*}"
export DOCKER_GC_PRUNE_VOLUMES="${DOCKER_GC_PRUNE_VOLUMES:-1}"
export DOCKER_GC_DRY_RUN="${DOCKER_GC_DRY_RUN:-0}"
export DOCKER_GC_DELETE_OLD_IMAGES="${DOCKER_GC_DELETE_OLD_IMAGES:-0}"
export DOCKER_GC_TIMEOUT="${DOCKER_GC_TIMEOUT:-900}"

mkdir -p "$(dirname "${LOG_FILE}")"
touch "${LOG_FILE}"
mkdir -p "${REMOTE_LOG_ROOT}/${CPU_WORKER_ID}"
ln -sfnT "${OPENCLAW_REMOTE_LOG_DIR}" "${REMOTE_LOG_ROOT}/${CPU_WORKER_ID}/latest_watchdog" 2>/dev/null || true

cd "${REPO_ROOT}"
exec > >(tee -a "${LOG_FILE}") 2>&1

echo "========================================"
echo "  OpenClaw docker watchdog"
echo "  repo:       ${REPO_ROOT}"
echo "  worker_id:  ${CPU_WORKER_ID}"
echo "  run_id:     ${OPENCLAW_REMOTE_RUN_ID}"
echo "  log_dir:    ${OPENCLAW_REMOTE_LOG_DIR}"
echo "  log_file:   ${LOG_FILE}"
echo "  pool:       ${POOL_HOST}:${POOL_PORT}"
echo "  docker_gc:  enabled=${WATCHDOG_DOCKER_STORAGE_GC} trigger=${DOCKER_GC_TRIGGER_USED_PCT}% target=${DOCKER_GC_TARGET_USED_PCT}% dry_run=${DOCKER_GC_DRY_RUN} delete_old_images=${DOCKER_GC_DELETE_OLD_IMAGES}"
echo "  resetstorm: repair=${POOL_RESET_STORM_REPAIR} min_resetting=${POOL_RESET_STORM_MIN_RESETTING} ratio=${POOL_RESET_STORM_RATIO_PCT}% min_age=${POOL_RESET_STORM_MIN_AGE}s checks=${POOL_RESET_STORM_STUCK_CHECKS}"
echo "========================================"

exec bash terminal-rl/remote/docker_watchdog_v2.sh
