#!/usr/bin/env bash
# CPU-worker pool_server launcher for SetA/terminal-rl.
#
# Runs in the foreground. Start it inside tmux/screen or redirect it from the
# caller if you want it detached.

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/mnt/shared-storage-user/puyuan/code/OpenClaw-RL}"
cd "${REPO_ROOT}"

RUNS_ROOT="${RUNS_ROOT:-${REPO_ROOT}/runs}"
if [[ -n "${RUN_DIR:-}" ]]; then
    DEFAULT_REMOTE_LOG_ROOT="${RUN_DIR}/remote_logs"
elif [[ -n "${RUN_ID:-}" ]]; then
    DEFAULT_REMOTE_LOG_ROOT="${RUNS_ROOT}/${RUN_ID}/remote_logs"
else
    DEFAULT_REMOTE_LOG_ROOT="${RUNS_ROOT}/remote_logs"
fi
REMOTE_LOG_ROOT="${REMOTE_LOG_ROOT:-${DEFAULT_REMOTE_LOG_ROOT}}"
CPU_WORKER_ID="${CPU_WORKER_ID:-$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo unknown-worker)}"
CPU_WORKER_ID="$(printf '%s' "${CPU_WORKER_ID}" | tr -c 'A-Za-z0-9_.-' '_')"
OPENCLAW_REMOTE_RUN_ID="${OPENCLAW_REMOTE_RUN_ID:-$(date +%Y%m%d_%H%M%S)_pid$$}"
OPENCLAW_REMOTE_LOG_DIR="${OPENCLAW_REMOTE_LOG_DIR:-${REMOTE_LOG_ROOT}/${CPU_WORKER_ID}/${OPENCLAW_REMOTE_RUN_ID}}"
export RUNS_ROOT REMOTE_LOG_ROOT CPU_WORKER_ID OPENCLAW_REMOTE_RUN_ID OPENCLAW_REMOTE_LOG_DIR
export CPU_POOL_LOG="${CPU_POOL_LOG:-${OPENCLAW_REMOTE_LOG_DIR}/cpu_pool.log}"
export CPU_ERR_LOG="${CPU_ERR_LOG:-${OPENCLAW_REMOTE_LOG_DIR}/cpu_err.log}"
mkdir -p "${OPENCLAW_REMOTE_LOG_DIR}" "${REMOTE_LOG_ROOT}/${CPU_WORKER_ID}"
ln -sfnT "${OPENCLAW_REMOTE_LOG_DIR}" "${REMOTE_LOG_ROOT}/${CPU_WORKER_ID}/latest_server" 2>/dev/null || true

if [ -f "${REPO_ROOT}/.venv/bin/activate" ]; then
    # shellcheck disable=SC1091
    source "${REPO_ROOT}/.venv/bin/activate"
fi

# Capacity. Keep the default high for most parallel-safe tasks, then serialize
# known compose-unsafe task ids through WORKER_SERIAL_TASK_IDS.
export WORKER_MAX_TASKS="${WORKER_MAX_TASKS:-16}"
export WORKER_MAX_RUNS_PER_TASK="${WORKER_MAX_RUNS_PER_TASK:-8}"
export WORKER_SERIAL_TASK_IDS="${WORKER_SERIAL_TASK_IDS:-892,1133}"
export WORKER_TASK_MAX_RUNS_OVERRIDES="${WORKER_TASK_MAX_RUNS_OVERRIDES:-}"
export WORKER_AUTO_SERIALIZE_UNSAFE_COMPOSE="${WORKER_AUTO_SERIALIZE_UNSAFE_COMPOSE:-0}"
export WORKER_MAX_CONCURRENT_CLOSES="${WORKER_MAX_CONCURRENT_CLOSES:-16}"
export WORKER_MAX_CONCURRENT_BUILDS="${WORKER_MAX_CONCURRENT_BUILDS:-2}"
export WORKER_MAX_CONCURRENT_RESETS="${WORKER_MAX_CONCURRENT_RESETS:-16}"
export WORKER_RESET_ADMISSION_TIMEOUT="${WORKER_RESET_ADMISSION_TIMEOUT:-30}"
export WORKER_RESET_BACKLOG_RETRY_AFTER="${WORKER_RESET_BACKLOG_RETRY_AFTER:-10}"
export WORKER_RUN_IDLE_TTL="${WORKER_RUN_IDLE_TTL:-180}"
export ENV_SERVER_PORT="${ENV_SERVER_PORT:-18081}"

# Timeouts and admission guards. Reset may include image build plus compose
# startup, so keep the server-side budget larger than either phase alone.
export WORKER_CLOSE_TASK_TIMEOUT="${WORKER_CLOSE_TASK_TIMEOUT:-45}"
export WORKER_CLOSE_QUEUE_TIMEOUT="${WORKER_CLOSE_QUEUE_TIMEOUT:-${WORKER_CLOSE_TASK_TIMEOUT}}"
export WORKER_CLOSE_SESSION_TIMEOUT="${WORKER_CLOSE_SESSION_TIMEOUT:-60}"
export WORKER_ALLOCATED_TTL="${WORKER_ALLOCATED_TTL:-60}"  # 120→60s: CRITICAL fix for slot accumulation
export ENSURE_IMAGE_TIMEOUT="${ENSURE_IMAGE_TIMEOUT:-1200}"
export RESET_SESSION_TIMEOUT="${RESET_SESSION_TIMEOUT:-600}"
export WORKER_RESET_OPERATION_TIMEOUT="${WORKER_RESET_OPERATION_TIMEOUT:-1920}"
export WORKER_RESETTING_TTL="${WORKER_RESETTING_TTL:-2100}"
export WORKER_DOCKER_BUILD_QUEUE_TIMEOUT="${WORKER_DOCKER_BUILD_QUEUE_TIMEOUT:-90}"
export WORKER_DOCKER_BUILD_BACKLOG_RETRY_AFTER="${WORKER_DOCKER_BUILD_BACKLOG_RETRY_AFTER:-15}"
export WORKER_RESET_TIMEOUT_RETRY_AFTER="${WORKER_RESET_TIMEOUT_RETRY_AFTER:-15}"
export WORKER_CLOSING_REQUESTED_TTL="${WORKER_CLOSING_REQUESTED_TTL:-300}"
export WORKER_PIDS_PAUSE_ALLOCATE_PCT="${WORKER_PIDS_PAUSE_ALLOCATE_PCT:-80}"
export WORKER_PIDS_REJECT_RESET_PCT="${WORKER_PIDS_REJECT_RESET_PCT:-85}"
export WORKER_PIDS_MIN_FREE_ALLOCATE="${WORKER_PIDS_MIN_FREE_ALLOCATE:-6000}"
export WORKER_PIDS_MIN_FREE_RESET="${WORKER_PIDS_MIN_FREE_RESET:-4000}"
# P0 fix: Lower shim thresholds to trigger proactive cleanup earlier
export WORKER_SHIM_PAUSE_ALLOCATE="${WORKER_SHIM_PAUSE_ALLOCATE:-160}"  # 180→160: cleanup before hitting critical
export WORKER_SHIM_REJECT_RESET="${WORKER_SHIM_REJECT_RESET:-200}"  # 220→200: more headroom
export WORKER_PENDING_CLOSES_PAUSE_ALLOCATE="${WORKER_PENDING_CLOSES_PAUSE_ALLOCATE:-32}"
export WORKER_PENDING_CLOSES_REJECT_RESET="${WORKER_PENDING_CLOSES_REJECT_RESET:-64}"
export WORKER_DOCKER_CLI_TIMEOUT="${WORKER_DOCKER_CLI_TIMEOUT:-3}"
export WORKER_DOCKER_DEGRADED_FAIL_STREAK="${WORKER_DOCKER_DEGRADED_FAIL_STREAK:-2}"
export WORKER_DOCKER_DEGRADED_COOLDOWN="${WORKER_DOCKER_DEGRADED_COOLDOWN:-120}"
export WORKER_PRESSURE_CACHE_TTL="${WORKER_PRESSURE_CACHE_TTL:-5}"
export WORKER_RESET_STORM_GUARD="${WORKER_RESET_STORM_GUARD:-1}"
export WORKER_RESET_STORM_BLOCK_ALLOCATE="${WORKER_RESET_STORM_BLOCK_ALLOCATE:-1}"
export WORKER_RESET_STORM_MIN_RESETTING="${WORKER_RESET_STORM_MIN_RESETTING:-32}"
export WORKER_RESET_STORM_MIN_AGE="${WORKER_RESET_STORM_MIN_AGE:-180}"
export WORKER_RESET_STORM_RATIO_PCT="${WORKER_RESET_STORM_RATIO_PCT:-50}"
export CONTAINER_PIDS_LIMIT="${CONTAINER_PIDS_LIMIT:-64}"
export CONTAINER_MEMORY_LIMIT="${CONTAINER_MEMORY_LIMIT:-16g}"

# Preflight and Docker cleanup. This worker is assumed dedicated to OpenClaw
# experiments, so broad cleanup is allowed to remove stale task containers.
export PREFLIGHT_KILL_ORPHAN_RUNNING="${PREFLIGHT_KILL_ORPHAN_RUNNING:-1}"
export SKIP_PREFLIGHT_CLEANUP="${SKIP_PREFLIGHT_CLEANUP:-0}"
export FINAL_DOCKER_CLEANUP="${FINAL_DOCKER_CLEANUP:-1}"
export FINAL_DOCKER_CLEANUP_TIMEOUT="${FINAL_DOCKER_CLEANUP_TIMEOUT:-90}"
export POOL_SERVER_SHUTDOWN_GRACE="${POOL_SERVER_SHUTDOWN_GRACE:-60}"
export TERMINAL_ENV_FORCE_DOCKER_CLEANUP="${TERMINAL_ENV_FORCE_DOCKER_CLEANUP:-1}"
export TERMINAL_ENV_FORCE_DOCKER_CLEANUP_BROAD="${TERMINAL_ENV_FORCE_DOCKER_CLEANUP_BROAD:-1}"
export TERMINAL_ENV_FORCE_DOCKER_CLEANUP_ALWAYS="${TERMINAL_ENV_FORCE_DOCKER_CLEANUP_ALWAYS:-1}"
export TERMINAL_ENV_FORCE_DOCKER_CLEANUP_TIMEOUT="${TERMINAL_ENV_FORCE_DOCKER_CLEANUP_TIMEOUT:-20}"
export TERMINAL_ENV_DOCKER_CLEANUP_WORKERS="${TERMINAL_ENV_DOCKER_CLEANUP_WORKERS:-8}"
export WORKER_SHUTDOWN_FORCE_CLEANUP_TIMEOUT="${WORKER_SHUTDOWN_FORCE_CLEANUP_TIMEOUT:-120}"
export TERMINAL_ENV_FAST_CLOSE="${TERMINAL_ENV_FAST_CLOSE:-1}"
export TERMINAL_ENV_SKIP_UNBOUNDED_STOP="${TERMINAL_ENV_SKIP_UNBOUNDED_STOP:-1}"
export TERMINAL_ENV_FAST_CLOSE_STOP_TIMEOUT="${TERMINAL_ENV_FAST_CLOSE_STOP_TIMEOUT:-5}"

# Repair stale in-memory pending close tasks. These are not Docker containers;
# they are asyncio close tasks inside pool_server.
export WORKER_REPAIR_PENDING_CLOSES="${WORKER_REPAIR_PENDING_CLOSES:-1}"
export WORKER_REPAIR_PENDING_CLOSES_MAX_ACTIVE_RUNS="${WORKER_REPAIR_PENDING_CLOSES_MAX_ACTIVE_RUNS:--1}"
export WORKER_REPAIR_PENDING_CLOSES_CANCEL_TIMEOUT="${WORKER_REPAIR_PENDING_CLOSES_CANCEL_TIMEOUT:-5}"
export WORKER_REPAIR_PENDING_CLOSES_MIN_AGE="${WORKER_REPAIR_PENDING_CLOSES_MIN_AGE:-45}"
export WORKER_REPAIR_STALE_RUNS="${WORKER_REPAIR_STALE_RUNS:-1}"
export WORKER_REPAIR_STALE_RUNS_MIN_AGE="${WORKER_REPAIR_STALE_RUNS_MIN_AGE:-0}"
export WORKER_REPAIR_STALE_RUNS_MAX_REPAIRS="${WORKER_REPAIR_STALE_RUNS_MAX_REPAIRS:-20}"
export WORKER_REPAIR_CLOSE_REQUESTED_RUNS="${WORKER_REPAIR_CLOSE_REQUESTED_RUNS:-1}"
export WORKER_REPAIR_CLOSE_REQUESTED_MIN_AGE="${WORKER_REPAIR_CLOSE_REQUESTED_MIN_AGE:-0}"
export WORKER_REPAIR_CLOSE_REQUESTED_MAX_REPAIRS="${WORKER_REPAIR_CLOSE_REQUESTED_MAX_REPAIRS:-20}"
export WORKER_REPAIR_RESETTING_RUNS="${WORKER_REPAIR_RESETTING_RUNS:-1}"
export WORKER_REPAIR_RESETTING_MIN_AGE="${WORKER_REPAIR_RESETTING_MIN_AGE:-2100}"  # match WORKER_RESETTING_TTL
export WORKER_REPAIR_RESETTING_MAX_REPAIRS="${WORKER_REPAIR_RESETTING_MAX_REPAIRS:-64}"
export WORKER_CLOSE_REQUESTED_FORCE_RELEASE="${WORKER_CLOSE_REQUESTED_FORCE_RELEASE:-1}"
export WORKER_CLOSE_REQUESTED_FORCE_RELEASE_AFTER="${WORKER_CLOSE_REQUESTED_FORCE_RELEASE_AFTER:-120}"
export WORKER_ORPHAN_DOCKER_SWEEP="${WORKER_ORPHAN_DOCKER_SWEEP:-1}"
export WORKER_ORPHAN_DOCKER_SWEEP_INTERVAL="${WORKER_ORPHAN_DOCKER_SWEEP_INTERVAL:-180}"
export WORKER_ORPHAN_DOCKER_SWEEP_MIN_AGE="${WORKER_ORPHAN_DOCKER_SWEEP_MIN_AGE:-600}"
export WORKER_ORPHAN_DOCKER_SWEEP_MAX_REMOVE="${WORKER_ORPHAN_DOCKER_SWEEP_MAX_REMOVE:-64}"
export WORKER_ORPHAN_DOCKER_SWEEP_TIMEOUT="${WORKER_ORPHAN_DOCKER_SWEEP_TIMEOUT:-15}"
export WORKER_ORPHAN_DOCKER_SWEEP_BACKOFF_BASE="${WORKER_ORPHAN_DOCKER_SWEEP_BACKOFF_BASE:-120}"
export WORKER_ORPHAN_DOCKER_SWEEP_BACKOFF_MAX="${WORKER_ORPHAN_DOCKER_SWEEP_BACKOFF_MAX:-900}"
export WORKER_AUTO_REPAIR_ON_CAPACITY="${WORKER_AUTO_REPAIR_ON_CAPACITY:-1}"
export WORKER_AUTO_REPAIR_CLOSE_REQUESTED_MIN_AGE="${WORKER_AUTO_REPAIR_CLOSE_REQUESTED_MIN_AGE:-0}"
export WORKER_AUTO_REPAIR_STALE_MIN_AGE="${WORKER_AUTO_REPAIR_STALE_MIN_AGE:-0}"
export WORKER_AUTO_REPAIR_MAX_REPAIRS="${WORKER_AUTO_REPAIR_MAX_REPAIRS:-40}"  # 20→40: aggressive cleanup during exhaustion

# Avoid duplicate concurrent builds for the same task image.
export WORKER_DOCKER_BUILD_DEDUP="${WORKER_DOCKER_BUILD_DEDUP:-1}"
export WORKER_DOCKER_BUILD_SKIP_EXISTING="${WORKER_DOCKER_BUILD_SKIP_EXISTING:-1}"
export WORKER_DOCKER_BUILD_FAILED_TTL="${WORKER_DOCKER_BUILD_FAILED_TTL:-3600}"
export WORKER_DOCKER_TASK_BLACKLIST_TTL="${WORKER_DOCKER_TASK_BLACKLIST_TTL:-86400}"
export WORKER_DOCKERFILE_PRECHECK="${WORKER_DOCKERFILE_PRECHECK:-1}"
export WORKER_TASK_IMAGE_RETRY_AFTER="${WORKER_TASK_IMAGE_RETRY_AFTER:-300}"

# ClawSentry is not needed for pure SetA outcome-reward baselines.
export CLAWSENTRY_NEEDED="${CLAWSENTRY_NEEDED:-0}"

echo "========================================"
echo "  OpenClaw pool_server"
echo "  repo:                 ${REPO_ROOT}"
echo "  python:               $(command -v python || true)"
echo "  port:                 ${ENV_SERVER_PORT}"
echo "  worker_id:            ${CPU_WORKER_ID}"
echo "  run_id:               ${OPENCLAW_REMOTE_RUN_ID}"
echo "  log_dir:              ${OPENCLAW_REMOTE_LOG_DIR}"
echo "  server_log:           ${CPU_POOL_LOG}"
echo "  err_log:              ${CPU_ERR_LOG}"
echo "  max_tasks:            ${WORKER_MAX_TASKS}"
echo "  max_runs_per_task:    ${WORKER_MAX_RUNS_PER_TASK}"
echo "  serial_task_ids:      ${WORKER_SERIAL_TASK_IDS}"
echo "  task_run_overrides:   ${WORKER_TASK_MAX_RUNS_OVERRIDES:-<none>}"
echo "  auto_serial_compose:  ${WORKER_AUTO_SERIALIZE_UNSAFE_COMPOSE}"
echo "  concurrent_closes:    ${WORKER_MAX_CONCURRENT_CLOSES}"
echo "  concurrent_builds:    ${WORKER_MAX_CONCURRENT_BUILDS}"
echo "  concurrent_resets:    ${WORKER_MAX_CONCURRENT_RESETS} admission_timeout=${WORKER_RESET_ADMISSION_TIMEOUT}s retry_after=${WORKER_RESET_BACKLOG_RETRY_AFTER}s"
echo "  build_queue_timeout:  ${WORKER_DOCKER_BUILD_QUEUE_TIMEOUT}s retry_after=${WORKER_DOCKER_BUILD_BACKLOG_RETRY_AFTER}s"
echo "  idle_ttl:             ${WORKER_RUN_IDLE_TTL}s"
echo "  close_timeout:        queue=${WORKER_CLOSE_QUEUE_TIMEOUT}s session=${WORKER_CLOSE_SESSION_TIMEOUT}s legacy=${WORKER_CLOSE_TASK_TIMEOUT}s"
echo "  reset_timeout:        ensure_image=${ENSURE_IMAGE_TIMEOUT}s reset_session=${RESET_SESSION_TIMEOUT}s operation=${WORKER_RESET_OPERATION_TIMEOUT}s stale_ttl=${WORKER_RESETTING_TTL}s"
echo "  stale_ttl:            allocated=${WORKER_ALLOCATED_TTL}s resetting=${WORKER_RESETTING_TTL}s closing_requested=${WORKER_CLOSING_REQUESTED_TTL}s"
echo "  pids_guard:           allocate=${WORKER_PIDS_PAUSE_ALLOCATE_PCT}%/${WORKER_PIDS_MIN_FREE_ALLOCATE}free reset=${WORKER_PIDS_REJECT_RESET_PCT}%/${WORKER_PIDS_MIN_FREE_RESET}free"
echo "  shim_guard:           allocate=${WORKER_SHIM_PAUSE_ALLOCATE} reset=${WORKER_SHIM_REJECT_RESET}"
echo "  pending_close_guard:  allocate=${WORKER_PENDING_CLOSES_PAUSE_ALLOCATE} reset=${WORKER_PENDING_CLOSES_REJECT_RESET}"
echo "  container_limits:     pids=${CONTAINER_PIDS_LIMIT} memory=${CONTAINER_MEMORY_LIMIT}"
echo "  preflight_cleanup:    skip=${SKIP_PREFLIGHT_CLEANUP} kill_orphans=${PREFLIGHT_KILL_ORPHAN_RUNNING}"
echo "  final_cleanup:        enabled=${FINAL_DOCKER_CLEANUP} timeout=${FINAL_DOCKER_CLEANUP_TIMEOUT}s shutdown_grace=${POOL_SERVER_SHUTDOWN_GRACE}s"
echo "  force_cleanup:        enabled=${TERMINAL_ENV_FORCE_DOCKER_CLEANUP} broad=${TERMINAL_ENV_FORCE_DOCKER_CLEANUP_BROAD} always=${TERMINAL_ENV_FORCE_DOCKER_CLEANUP_ALWAYS} workers=${TERMINAL_ENV_DOCKER_CLEANUP_WORKERS} batch_timeout=${WORKER_SHUTDOWN_FORCE_CLEANUP_TIMEOUT}s"
echo "  fast_close:           enabled=${TERMINAL_ENV_FAST_CLOSE} skip_unbounded_stop=${TERMINAL_ENV_SKIP_UNBOUNDED_STOP} stop_timeout=${TERMINAL_ENV_FAST_CLOSE_STOP_TIMEOUT}s"
echo "  pending_repair:       enabled=${WORKER_REPAIR_PENDING_CLOSES} max_active=${WORKER_REPAIR_PENDING_CLOSES_MAX_ACTIVE_RUNS} min_age=${WORKER_REPAIR_PENDING_CLOSES_MIN_AGE}s"
echo "  stale_run_repair:     enabled=${WORKER_REPAIR_STALE_RUNS} min_age=${WORKER_REPAIR_STALE_RUNS_MIN_AGE}s max_repairs=${WORKER_REPAIR_STALE_RUNS_MAX_REPAIRS}"
echo "  close_req_repair:     enabled=${WORKER_REPAIR_CLOSE_REQUESTED_RUNS} min_age=${WORKER_REPAIR_CLOSE_REQUESTED_MIN_AGE}s max_repairs=${WORKER_REPAIR_CLOSE_REQUESTED_MAX_REPAIRS}"
echo "  resetting_repair:     enabled=${WORKER_REPAIR_RESETTING_RUNS} min_age=${WORKER_REPAIR_RESETTING_MIN_AGE}s max_repairs=${WORKER_REPAIR_RESETTING_MAX_REPAIRS}"
echo "  close_req_release:    enabled=${WORKER_CLOSE_REQUESTED_FORCE_RELEASE} after=${WORKER_CLOSE_REQUESTED_FORCE_RELEASE_AFTER}s"
echo "  orphan_sweep:         enabled=${WORKER_ORPHAN_DOCKER_SWEEP} interval=${WORKER_ORPHAN_DOCKER_SWEEP_INTERVAL}s min_age=${WORKER_ORPHAN_DOCKER_SWEEP_MIN_AGE}s max_remove=${WORKER_ORPHAN_DOCKER_SWEEP_MAX_REMOVE} timeout=${WORKER_ORPHAN_DOCKER_SWEEP_TIMEOUT}s"
echo "  docker_degraded:      fail_streak=${WORKER_DOCKER_DEGRADED_FAIL_STREAK} cooldown=${WORKER_DOCKER_DEGRADED_COOLDOWN}s reset_storm=${WORKER_RESET_STORM_GUARD} min=${WORKER_RESET_STORM_MIN_RESETTING} age=${WORKER_RESET_STORM_MIN_AGE}s ratio=${WORKER_RESET_STORM_RATIO_PCT}%"
echo "  capacity_auto_repair: enabled=${WORKER_AUTO_REPAIR_ON_CAPACITY} close_min_age=${WORKER_AUTO_REPAIR_CLOSE_REQUESTED_MIN_AGE}s stale_min_age=${WORKER_AUTO_REPAIR_STALE_MIN_AGE}s max_repairs=${WORKER_AUTO_REPAIR_MAX_REPAIRS}"
echo "  build_dedup:          enabled=${WORKER_DOCKER_BUILD_DEDUP} skip_existing=${WORKER_DOCKER_BUILD_SKIP_EXISTING} failed_ttl=${WORKER_DOCKER_BUILD_FAILED_TTL}s blacklist_ttl=${WORKER_DOCKER_TASK_BLACKLIST_TTL}s precheck=${WORKER_DOCKERFILE_PRECHECK}"
echo "========================================"

exec bash terminal-rl/remote/run_pool_server_pu_v2.sh
