#!/usr/bin/env bash
# SETA-only adaptive exploration v0615 launch for Qwen3-8B.
#
# The 06-15 version keeps the UCB+dualadv stack, uses SETA raw pass-rate for
# UCB normalized-base updates, keeps nodynamic-compatible continuation when
# docker-env fails, and makes truncated/failed trajectories less trusted.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y-%m-%d_%H%M%S)}"
NUM_GPUS="${NUM_GPUS:-8}"

DATASET="${DATASET:-seta}"
ALGO="${ALGO:-dapo}"
HARNESS_OPTION="${HARNESS_OPTION:-camel-agent}"

RUN_ID="${RUN_ID:-terminal-rl_qwen3-8b_${NUM_GPUS}gpu_seta_dapo_nodynamic_exploration_simhash_life_fp_ucb_v0615_envtolerant_fastwarm_dualadv_think_${RUN_TIMESTAMP}}"
RUN_NAME="${RUN_NAME:-${RUN_ID}}"

# Keep rollout geometry identical to baseline and prior exploration runs.
ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-8}"
N_SAMPLES="${N_SAMPLES:-8}"
MAX_TURN="${MAX_TURN:-10}"
MAX_CKPT_KEEP="${MAX_CKPT_KEEP:-2}"
TRAJECTORY_SAVE_INTERVAL="${TRAJECTORY_SAVE_INTERVAL:-10}"
TRAJECTORY_SAVE_POLICY="${TRAJECTORY_SAVE_POLICY:-task_timeseries}"
TRAJECTORY_TASK_SAVE_INTERVAL="${TRAJECTORY_TASK_SAVE_INTERVAL:-5}"
TRAJECTORY_TASK_MAX_PER_STEP="${TRAJECTORY_TASK_MAX_PER_STEP:-2}"
TRAJECTORY_TASK_MAX_PER_TASK="${TRAJECTORY_TASK_MAX_PER_TASK:-24}"
TRAJECTORY_MAX_TOTAL="${TRAJECTORY_MAX_TOTAL:-5000}"
TRAJECTORY_SAVE_REWARD_STRATA="${TRAJECTORY_SAVE_REWARD_STRATA:-best,worst}"
TRAJECTORY_SAVE_LOG_DECISIONS="${TRAJECTORY_SAVE_LOG_DECISIONS:-0}"
DAPO_DYNAMIC_SAMPLING="${DAPO_DYNAMIC_SAMPLING:-0}"
EXTRA_DAPO_ARGS="${EXTRA_DAPO_ARGS:-}"
# Keep training alive through transient docker-server instability by default.
# Set DAPO_FAILED_GROUP_ABORT_MIN_GROUPS=8 to fail fast on all-failed rollout batches.
DAPO_FAILED_GROUP_ABORT_MIN_GROUPS="${DAPO_FAILED_GROUP_ABORT_MIN_GROUPS:-0}"
DAPO_FAILED_GROUP_ABORT_RATIO="${DAPO_FAILED_GROUP_ABORT_RATIO:-1.0}"
if (( DAPO_FAILED_GROUP_ABORT_MIN_GROUPS > 0 )); then
  if [[ " ${EXTRA_DAPO_ARGS} " != *" --dynamic-sampling-failed-group-abort-min-groups "* ]]; then
    EXTRA_DAPO_ARGS="${EXTRA_DAPO_ARGS} --dynamic-sampling-failed-group-abort-min-groups ${DAPO_FAILED_GROUP_ABORT_MIN_GROUPS}"
  fi
  if [[ " ${EXTRA_DAPO_ARGS} " != *" --dynamic-sampling-failed-group-abort-ratio "* ]]; then
    EXTRA_DAPO_ARGS="${EXTRA_DAPO_ARGS} --dynamic-sampling-failed-group-abort-ratio ${DAPO_FAILED_GROUP_ABORT_RATIO}"
  fi
fi
ROUTER_READY_WAIT_FOREVER="${ROUTER_READY_WAIT_FOREVER:-1}"
AUTO_CLOSE_STALE_WORKER_RUNS="${AUTO_CLOSE_STALE_WORKER_RUNS:-1}"
STALE_WORKER_CLOSE_INTERVAL="${STALE_WORKER_CLOSE_INTERVAL:-10}"
STALE_WORKER_CLOSE_TIMEOUT="${STALE_WORKER_CLOSE_TIMEOUT:-10}"
STALE_WORKER_REPAIR_MIN_AGE="${STALE_WORKER_REPAIR_MIN_AGE:-0}"
STALE_WORKER_REPAIR_MAX_REPAIRS="${STALE_WORKER_REPAIR_MAX_REPAIRS:-20}"
WORKER_URLS_FILE="${WORKER_URLS_FILE:-${SCRIPT_DIR}/worker_urls.txt}"
WORKER_URLS_RELOAD_INTERVAL="${WORKER_URLS_RELOAD_INTERVAL:-120}"
SLIME_SKIP_ZERO_TRAINABLE_ROLLOUT="${SLIME_SKIP_ZERO_TRAINABLE_ROLLOUT:-1}"
SLIME_SKIP_ZERO_TRAINABLE_TRAIN="${SLIME_SKIP_ZERO_TRAINABLE_TRAIN:-1}"

# SETA reward defaults.
SETA_SAFETY="${SETA_SAFETY:-none}"
SAFETY_REWARD_COEF="${SAFETY_REWARD_COEF:-0}"
TERMINAL_WANDB_METRIC_PROFILE="${TERMINAL_WANDB_METRIC_PROFILE:-compact}"

# Adaptive UCB exploration defaults.
CUSTOM_CONFIG_PATH="${CUSTOM_CONFIG_PATH:-${SCRIPT_DIR}/configs/rollout_qwen3_think.yaml}"
EXPLORATION_PROFILE="${EXPLORATION_PROFILE:-spear_lite}"
EXPLORE_THINK_MODE="${EXPLORE_THINK_MODE:-1}"
EXPLORE_INTRINSIC="${EXPLORE_INTRINSIC:-1}"
EXPLORE_INTRINSIC_COEF="${EXPLORE_INTRINSIC_COEF:-0.015}"
EXPLORE_INTRINSIC_SCHEDULE="${EXPLORE_INTRINSIC_SCHEDULE:-cosine}"
EXPLORE_INTRINSIC_DECAY_STEPS="${EXPLORE_INTRINSIC_DECAY_STEPS:-120}"
EXPLORE_INTRINSIC_REDUCER="${EXPLORE_INTRINSIC_REDUCER:-mean}"
EXPLORE_INTRINSIC_GRANULARITY="${EXPLORE_INTRINSIC_GRANULARITY:-signature}"
EXPLORE_INTRINSIC_SCOPE="${EXPLORE_INTRINSIC_SCOPE:-episode}"
EXPLORE_SCORE_BONUS_COMPONENTS="${EXPLORE_SCORE_BONUS_COMPONENTS:-none}"

EXPLORE_AGENT57_LITE="${EXPLORE_AGENT57_LITE:-1}"
EXPLORE_AGENT57_K="${EXPLORE_AGENT57_K:-8}"
EXPLORE_AGENT57_ARM_BETAS="${EXPLORE_AGENT57_ARM_BETAS:-0,0.002,0.004,0.006,0.008,0.01,0.015,0.02}"
EXPLORE_AGENT57_COMBINE_MODE="${EXPLORE_AGENT57_COMBINE_MODE:-ngu_lite}"
EXPLORE_AGENT57_NGU_EPISODIC_SOURCE="${EXPLORE_AGENT57_NGU_EPISODIC_SOURCE:-signature_intrinsic}"
EXPLORE_AGENT57_NGU_EPISODIC_REDUCER="${EXPLORE_AGENT57_NGU_EPISODIC_REDUCER:-${EXPLORE_INTRINSIC_REDUCER}}"
EXPLORE_AGENT57_NGU_LIFE_MOD_MODE="${EXPLORE_AGENT57_NGU_LIFE_MOD_MODE:-standardized_softplus}"
EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP="${EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP:-5.0}"
EXPLORE_AGENT57_NGU_MOD_CLIP="${EXPLORE_AGENT57_NGU_MOD_CLIP:-5.0}"
EXPLORE_AGENT57_MAX_BONUS="${EXPLORE_AGENT57_MAX_BONUS:-0.05}"
EXPLORE_AGENT57_CONTROLLER="${EXPLORE_AGENT57_CONTROLLER:-ucb}"
EXPLORE_AGENT57_ARM_TEMPERATURES="${EXPLORE_AGENT57_ARM_TEMPERATURES:-1,1,1,1.02,1.02,1.05,1.05,1.08}"
EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS="${EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS:-24}"
EXPLORE_AGENT57_ARM_TOP_PS="${EXPLORE_AGENT57_ARM_TOP_PS:-1,1,1,1,1,1,1,1}"
EXPLORE_AGENT57_ARM_TOP_KS="${EXPLORE_AGENT57_ARM_TOP_KS:-}"
EXPLORE_AGENT57_UCB_C="${EXPLORE_AGENT57_UCB_C:-0.5}"
EXPLORE_AGENT57_UCB_WINDOW="${EXPLORE_AGENT57_UCB_WINDOW:-256}"
EXPLORE_AGENT57_UCB_EPSILON="${EXPLORE_AGENT57_UCB_EPSILON:-0.02}"
EXPLORE_AGENT57_UCB_MIN_PER_ARM="${EXPLORE_AGENT57_UCB_MIN_PER_ARM:-4}"
EXPLORE_AGENT57_UCB_VALUE="${EXPLORE_AGENT57_UCB_VALUE:-normalized_base}"
EXPLORE_AGENT57_UCB_DATASET_AWARE="${EXPLORE_AGENT57_UCB_DATASET_AWARE:-1}"
EXPLORE_AGENT57_UCB_RANDOM_SEED="${EXPLORE_AGENT57_UCB_RANDOM_SEED:-20260605}"

EPISODIC_MEMORY_BACKEND="${EPISODIC_MEMORY_BACKEND:-simhash_knn}"
EXPLORE_AGENT57_EPISODIC_BACKEND="${EXPLORE_AGENT57_EPISODIC_BACKEND:-${EPISODIC_MEMORY_BACKEND}}"
EXPLORE_AGENT57_EPISODIC_CAPACITY="${EXPLORE_AGENT57_EPISODIC_CAPACITY:-4096}"
EXPLORE_AGENT57_EPISODIC_COUNT_DECAY="${EXPLORE_AGENT57_EPISODIC_COUNT_DECAY:-1.0}"
EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET="${EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET:-1}"
EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS="${EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS:-64}"
EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY="${EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY:-256}"
EXPLORE_AGENT57_EPISODIC_K="${EXPLORE_AGENT57_EPISODIC_K:-5}"
EXPLORE_AGENT57_EPISODIC_DISTANCE="${EXPLORE_AGENT57_EPISODIC_DISTANCE:-cosine}"
EXPLORE_AGENT57_EPISODIC_VECTOR_DIM="${EXPLORE_AGENT57_EPISODIC_VECTOR_DIM:-256}"
EXPLORE_AGENT57_EPISODIC_RANDOM_SEED="${EXPLORE_AGENT57_EPISODIC_RANDOM_SEED:-20260605}"
EXPLORE_AGENT57_EPISODIC_OBS_MODE="${EXPLORE_AGENT57_EPISODIC_OBS_MODE:-fingerprint}"
EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN="${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN:-1}"
EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS="${EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS:-1}"
EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR="${EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR:-0.05}"

EXPLORE_AGENT57_LIFELONG="${EXPLORE_AGENT57_LIFELONG:-1}"
EXPLORE_AGENT57_LIFELONG_BACKEND="${EXPLORE_AGENT57_LIFELONG_BACKEND:-sqlite}"
EXPLORE_AGENT57_LIFELONG_COEF="${EXPLORE_AGENT57_LIFELONG_COEF:-0.005}"
EXPLORE_AGENT57_LIFELONG_CLIP="${EXPLORE_AGENT57_LIFELONG_CLIP:-2.0}"
EXPLORE_AGENT57_LIFELONG_WARMUP="${EXPLORE_AGENT57_LIFELONG_WARMUP:-64}"
EXPLORE_AGENT57_LIFELONG_COUNT_DECAY="${EXPLORE_AGENT57_LIFELONG_COUNT_DECAY:-0.995}"
EXPLORE_AGENT57_LIFELONG_CAPACITY="${EXPLORE_AGENT57_LIFELONG_CAPACITY:-200000}"
EXPLORE_AGENT57_LIFELONG_KEY_VERSION="${EXPLORE_AGENT57_LIFELONG_KEY_VERSION:-v2}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET="${EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET:-1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK:-1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN:-0}"
EXPLORE_AGENT57_LIFELONG_OBS_MODE="${EXPLORE_AGENT57_LIFELONG_OBS_MODE:-fingerprint}"
EXPLORE_AGENT57_LIFELONG_HIERARCHICAL="${EXPLORE_AGENT57_LIFELONG_HIERARCHICAL:-1}"
EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT="${EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT:-0.5}"
EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT="${EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT:-0.35}"
EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT="${EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT:-0.15}"
EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS="${EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS:-30000}"
EXPLORE_AGENT57_SQLITE_WAL="${EXPLORE_AGENT57_SQLITE_WAL:-0}"

EXPLORE_AGENT57_TRUST_GATE="${EXPLORE_AGENT57_TRUST_GATE:-soft}"
EXPLORE_AGENT57_TRUST_COMPLETED="${EXPLORE_AGENT57_TRUST_COMPLETED:-1.0}"
EXPLORE_AGENT57_TRUST_TRUNCATED="${EXPLORE_AGENT57_TRUST_TRUNCATED:-0.05}"
EXPLORE_AGENT57_TRUST_FAILED="${EXPLORE_AGENT57_TRUST_FAILED:-0.05}"
EXPLORE_AGENT57_TRUST_PARSE_ERROR="${EXPLORE_AGENT57_TRUST_PARSE_ERROR:-0.05}"
EXPLORE_AGENT57_TRUST_WARMUP="${EXPLORE_AGENT57_TRUST_WARMUP:-0.3}"

EXPLORE_ADVANTAGE_BONUS="${EXPLORE_ADVANTAGE_BONUS:-1}"
EXPLORE_ADVANTAGE_BONUS_MODE="${EXPLORE_ADVANTAGE_BONUS_MODE:-dual_stream}"
EXPLORE_ADVANTAGE_INTRINSIC_KEY="${EXPLORE_ADVANTAGE_INTRINSIC_KEY:-explore_agent57_intrinsic_signal}"
EXPLORE_ADVANTAGE_LAMBDA="${EXPLORE_ADVANTAGE_LAMBDA:-0.08}"
EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE="${EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE:-normalized_beta}"
EXPLORE_ADVANTAGE_TRUST_KEY="${EXPLORE_ADVANTAGE_TRUST_KEY:-explore_agent57_trust}"
EXPLORE_ADVANTAGE_BONUS_CLIP="${EXPLORE_ADVANTAGE_BONUS_CLIP:-0.5}"
EXPLORE_TRUNCATION_PENALTY="${EXPLORE_TRUNCATION_PENALTY:--0.03}"
EXPLORE_ADVANTAGE_TRUNCATION_PENALTY="${EXPLORE_ADVANTAGE_TRUNCATION_PENALTY:-${EXPLORE_TRUNCATION_PENALTY}}"

# Keep overlapping curiosity terms opt-in for clean ablation.
EXPLORE_CDE_ACTOR="${EXPLORE_CDE_ACTOR:-0}"
EXPLORE_LPRND="${EXPLORE_LPRND:-0}"
EXPLORE_SAFETY_FILTER="${EXPLORE_SAFETY_FILTER:-0}"

export RUN_TIMESTAMP NUM_GPUS RUN_ID RUN_NAME
export DATASET ALGO HARNESS_OPTION
export ROLLOUT_BATCH_SIZE N_SAMPLES MAX_TURN MAX_CKPT_KEEP TRAJECTORY_SAVE_INTERVAL DAPO_DYNAMIC_SAMPLING EXTRA_DAPO_ARGS
export DAPO_FAILED_GROUP_ABORT_MIN_GROUPS DAPO_FAILED_GROUP_ABORT_RATIO
export TRAJECTORY_SAVE_POLICY TRAJECTORY_TASK_SAVE_INTERVAL TRAJECTORY_TASK_MAX_PER_STEP
export TRAJECTORY_TASK_MAX_PER_TASK TRAJECTORY_MAX_TOTAL TRAJECTORY_SAVE_REWARD_STRATA
export TRAJECTORY_SAVE_LOG_DECISIONS
export ROUTER_READY_WAIT_FOREVER AUTO_CLOSE_STALE_WORKER_RUNS STALE_WORKER_CLOSE_INTERVAL STALE_WORKER_CLOSE_TIMEOUT
export STALE_WORKER_REPAIR_MIN_AGE STALE_WORKER_REPAIR_MAX_REPAIRS
export WORKER_URLS_FILE WORKER_URLS_RELOAD_INTERVAL SLIME_SKIP_ZERO_TRAINABLE_ROLLOUT SLIME_SKIP_ZERO_TRAINABLE_TRAIN
export SETA_SAFETY SAFETY_REWARD_COEF CUSTOM_CONFIG_PATH TERMINAL_WANDB_METRIC_PROFILE
export EXPLORATION_PROFILE EXPLORE_THINK_MODE
export EXPLORE_INTRINSIC EXPLORE_INTRINSIC_COEF EXPLORE_INTRINSIC_SCHEDULE EXPLORE_INTRINSIC_DECAY_STEPS
export EXPLORE_INTRINSIC_REDUCER EXPLORE_INTRINSIC_GRANULARITY EXPLORE_INTRINSIC_SCOPE EXPLORE_SCORE_BONUS_COMPONENTS
export EXPLORE_AGENT57_LITE EXPLORE_AGENT57_K EXPLORE_AGENT57_ARM_BETAS EXPLORE_AGENT57_COMBINE_MODE
export EXPLORE_AGENT57_NGU_EPISODIC_SOURCE EXPLORE_AGENT57_NGU_EPISODIC_REDUCER
export EXPLORE_AGENT57_NGU_LIFE_MOD_MODE EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP
export EXPLORE_AGENT57_NGU_MOD_CLIP EXPLORE_AGENT57_MAX_BONUS EXPLORE_AGENT57_CONTROLLER
export EXPLORE_AGENT57_ARM_TEMPERATURES EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS
export EXPLORE_AGENT57_ARM_TOP_PS EXPLORE_AGENT57_ARM_TOP_KS
export EXPLORE_AGENT57_UCB_C EXPLORE_AGENT57_UCB_WINDOW EXPLORE_AGENT57_UCB_EPSILON
export EXPLORE_AGENT57_UCB_MIN_PER_ARM EXPLORE_AGENT57_UCB_VALUE EXPLORE_AGENT57_UCB_DATASET_AWARE
export EXPLORE_AGENT57_UCB_RANDOM_SEED
export EPISODIC_MEMORY_BACKEND EXPLORE_AGENT57_EPISODIC_BACKEND EXPLORE_AGENT57_EPISODIC_CAPACITY
export EXPLORE_AGENT57_EPISODIC_COUNT_DECAY EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET
export EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY
export EXPLORE_AGENT57_EPISODIC_K EXPLORE_AGENT57_EPISODIC_DISTANCE EXPLORE_AGENT57_EPISODIC_VECTOR_DIM
export EXPLORE_AGENT57_EPISODIC_RANDOM_SEED EXPLORE_AGENT57_EPISODIC_OBS_MODE EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN
export EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR
export EXPLORE_AGENT57_LIFELONG EXPLORE_AGENT57_LIFELONG_BACKEND EXPLORE_AGENT57_LIFELONG_COEF
export EXPLORE_AGENT57_LIFELONG_CLIP EXPLORE_AGENT57_LIFELONG_WARMUP
export EXPLORE_AGENT57_LIFELONG_COUNT_DECAY EXPLORE_AGENT57_LIFELONG_CAPACITY
export EXPLORE_AGENT57_LIFELONG_KEY_VERSION EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET
export EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN EXPLORE_AGENT57_LIFELONG_OBS_MODE
export EXPLORE_AGENT57_LIFELONG_HIERARCHICAL EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT
export EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT
export EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS EXPLORE_AGENT57_SQLITE_WAL
export EXPLORE_AGENT57_TRUST_GATE EXPLORE_AGENT57_TRUST_COMPLETED EXPLORE_AGENT57_TRUST_TRUNCATED
export EXPLORE_AGENT57_TRUST_FAILED EXPLORE_AGENT57_TRUST_PARSE_ERROR EXPLORE_AGENT57_TRUST_WARMUP
export EXPLORE_ADVANTAGE_BONUS EXPLORE_ADVANTAGE_BONUS_MODE EXPLORE_ADVANTAGE_INTRINSIC_KEY
export EXPLORE_ADVANTAGE_LAMBDA EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE EXPLORE_ADVANTAGE_TRUST_KEY EXPLORE_ADVANTAGE_BONUS_CLIP
export EXPLORE_TRUNCATION_PENALTY EXPLORE_ADVANTAGE_TRUNCATION_PENALTY
export EXPLORE_CDE_ACTOR EXPLORE_LPRND EXPLORE_SAFETY_FILTER

exec bash "${SCRIPT_DIR}/terminal-rl_qwen3-8b_mixed_dapo_nodynamic_exploration_pu.sh" "$@"
