#!/usr/bin/env bash
# SETA-only adaptive exploration v0707 launch for Qwen3-8B.
#
# Baseline:
#   terminal-rl_qwen3-8b_seta_dapo_nodynamic_exploration_ucb_pu_v0629_3.sh
#
# Motivation:
#   v0629_3 makes intrinsic advantage visible by setting
#   EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE=none. That is stable, but it also makes
#   Agent57 beta arms mostly diagnostic because:
#     - score-space exploration is disabled by EXPLORE_SCORE_BONUS_COMPONENTS=none;
#     - post-norm intrinsic advantage no longer uses beta;
#     - per-arm temperatures are empty, so rollout behavior is the same.
#
# v0707 restores Agent57-style beta scaling in the post-normalized intrinsic
# stream, but keeps it bounded enough to remain visible:
#   B_int_i = clip(lambda * (beta_i / max_beta) * quality_gate_i * A_int_i, clip)
#
# It also adds a small post-warmup temperature ladder so UCB arms have a causal
# sampling-side difference, without returning to the larger high-temperature
# ladder that hurt raw reward in earlier runs.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y-%m-%d_%H%M%S)}"
NUM_GPUS="${NUM_GPUS:-8}"

EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN="${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN:-1}"
case "${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN,,}" in
    1|true|yes|on) EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN="1" ;;
    *) EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN="0" ;;
esac

EXPLORE_AGENT57_EPISODIC_TURN_MODE="${EXPLORE_AGENT57_EPISODIC_TURN_MODE:-bucket}"
case "${EXPLORE_AGENT57_EPISODIC_TURN_MODE,,}" in
    bucket|coarse) EXPLORE_AGENT57_EPISODIC_TURN_MODE="bucket" ;;
    phase|stage) EXPLORE_AGENT57_EPISODIC_TURN_MODE="phase" ;;
    none|off|0|false|no) EXPLORE_AGENT57_EPISODIC_TURN_MODE="none" ;;
    *) EXPLORE_AGENT57_EPISODIC_TURN_MODE="bucket" ;;
esac
if [[ "${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN}" == "0" ]]; then
    EXPLORE_AGENT57_EPISODIC_TURN_MODE="none"
fi
EPISODIC_TURN_TAG="epturn${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN}_${EXPLORE_AGENT57_EPISODIC_TURN_MODE}"

RUN_ID="${RUN_ID:-terminal-rl_qwen3-8b_${NUM_GPUS}gpu_seta_dapo_nodynamic_exploration_simhash_life_fp_ucb_v0707_betaadv_temp_lite_outcome_gate_${EPISODIC_TURN_TAG}_dualadv_think_${RUN_TIMESTAMP}}"
RUN_NAME="${RUN_NAME:-${RUN_ID}}"
WANDB_GROUP="${WANDB_GROUP:-qwen3-8b_seta_exploration_v0707_betaadv_temp_lite_${EPISODIC_TURN_TAG}}"

# Keep reward-space exploration off. Agent57 score-space bonus remains a metric;
# the training signal is the post-normalized intrinsic advantage below.
EXPLORE_SCORE_BONUS_COMPONENTS="${EXPLORE_SCORE_BONUS_COMPONENTS:-none}"

# Re-enable beta in the intrinsic advantage stream. The non-baseline beta ladder
# is denser at the low end than v0629, so arm 1/2 do not become numerically
# irrelevant after beta/max_beta normalization.
EXPLORE_AGENT57_ARM_BETAS="${EXPLORE_AGENT57_ARM_BETAS:-0,0.004,0.006,0.008,0.010,0.012,0.016,0.020}"
EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE="${EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE:-normalized_beta}"
EXPLORE_ADVANTAGE_LAMBDA="${EXPLORE_ADVANTAGE_LAMBDA:-0.08}"
EXPLORE_ADVANTAGE_BONUS_CLIP="${EXPLORE_ADVANTAGE_BONUS_CLIP:-0.35}"
EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE="${EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE:-constant}"
EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS="${EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS:-0}"

# Preserve v0629_3 outcome-aware guards.
EXPLORE_ADVANTAGE_GATE_MODE="${EXPLORE_ADVANTAGE_GATE_MODE:-outcome_status}"
EXPLORE_ADVANTAGE_OUTCOME_KEY="${EXPLORE_ADVANTAGE_OUTCOME_KEY:-raw_score}"
EXPLORE_ADVANTAGE_COMPLETED_FLOOR="${EXPLORE_ADVANTAGE_COMPLETED_FLOOR:-0.50}"
EXPLORE_ADVANTAGE_TRUNCATED_FLOOR="${EXPLORE_ADVANTAGE_TRUNCATED_FLOOR:-0.15}"
EXPLORE_ADVANTAGE_FAILED_FLOOR="${EXPLORE_ADVANTAGE_FAILED_FLOOR:-0.0}"
EXPLORE_ADVANTAGE_ABORTED_FLOOR="${EXPLORE_ADVANTAGE_ABORTED_FLOOR:-0.0}"
EXPLORE_TRUNCATION_PENALTY_OUTCOME_AWARE="${EXPLORE_TRUNCATION_PENALTY_OUTCOME_AWARE:-1}"

# Give UCB arms a small causal sampling-side difference after warmup. Keep arm 0
# and arm 1 at baseline temperature; the highest arm is only 1.03.
EXPLORE_AGENT57_KEEP_BASELINE="${EXPLORE_AGENT57_KEEP_BASELINE:-1}"
EXPLORE_AGENT57_ARM_TEMPERATURES="${EXPLORE_AGENT57_ARM_TEMPERATURES:-1.00,1.00,1.005,1.010,1.015,1.020,1.025,1.030}"
EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS="${EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS:-24}"
EXPLORE_AGENT57_ARM_TOP_PS="${EXPLORE_AGENT57_ARM_TOP_PS:-1,1,1,1,1,1,1,1}"
EXPLORE_AGENT57_ARM_TOP_KS="${EXPLORE_AGENT57_ARM_TOP_KS:-}"

# Keep v0629 UCB pressure unless explicitly overridden.
EXPLORE_AGENT57_CONTROLLER="${EXPLORE_AGENT57_CONTROLLER:-ucb}"
EXPLORE_AGENT57_UCB_C="${EXPLORE_AGENT57_UCB_C:-0.5}"
EXPLORE_AGENT57_UCB_WINDOW="${EXPLORE_AGENT57_UCB_WINDOW:-256}"
EXPLORE_AGENT57_UCB_EPSILON="${EXPLORE_AGENT57_UCB_EPSILON:-0.02}"
EXPLORE_AGENT57_UCB_MIN_PER_ARM="${EXPLORE_AGENT57_UCB_MIN_PER_ARM:-4}"
EXPLORE_AGENT57_UCB_VALUE="${EXPLORE_AGENT57_UCB_VALUE:-normalized_base}"
EXPLORE_AGENT57_UCB_DATASET_AWARE="${EXPLORE_AGENT57_UCB_DATASET_AWARE:-1}"
EXPLORE_AGENT57_UCB_RANDOM_SEED="${EXPLORE_AGENT57_UCB_RANDOM_SEED:-20260605}"

export RUN_TIMESTAMP NUM_GPUS RUN_ID RUN_NAME WANDB_GROUP
export EXPLORE_SCORE_BONUS_COMPONENTS
export EXPLORE_AGENT57_ARM_BETAS EXPLORE_AGENT57_KEEP_BASELINE
export EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE EXPLORE_ADVANTAGE_LAMBDA
export EXPLORE_ADVANTAGE_BONUS_CLIP EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE
export EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS
export EXPLORE_ADVANTAGE_GATE_MODE EXPLORE_ADVANTAGE_OUTCOME_KEY
export EXPLORE_ADVANTAGE_COMPLETED_FLOOR EXPLORE_ADVANTAGE_TRUNCATED_FLOOR
export EXPLORE_ADVANTAGE_FAILED_FLOOR EXPLORE_ADVANTAGE_ABORTED_FLOOR
export EXPLORE_TRUNCATION_PENALTY_OUTCOME_AWARE
export EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN EXPLORE_AGENT57_EPISODIC_TURN_MODE
export EXPLORE_AGENT57_ARM_TEMPERATURES EXPLORE_AGENT57_ARM_TEMPERATURE_WARMUP_ROLLOUTS
export EXPLORE_AGENT57_ARM_TOP_PS EXPLORE_AGENT57_ARM_TOP_KS
export EXPLORE_AGENT57_CONTROLLER EXPLORE_AGENT57_UCB_C EXPLORE_AGENT57_UCB_WINDOW
export EXPLORE_AGENT57_UCB_EPSILON EXPLORE_AGENT57_UCB_MIN_PER_ARM
export EXPLORE_AGENT57_UCB_VALUE EXPLORE_AGENT57_UCB_DATASET_AWARE
export EXPLORE_AGENT57_UCB_RANDOM_SEED

exec bash "${SCRIPT_DIR}/terminal-rl_qwen3-8b_seta_dapo_nodynamic_exploration_ucb_pu_v0629_3.sh" "$@"
