#!/usr/bin/env bash
# terminal-rl_qwen3-8b_mixed_dapo_nodynamic_exploration_pu.sh
# Mixed-data DAPO exploration wrapper without dynamic sampling.
#
# Defaults use the 2026-06-05 mixed DAPO Agent57/NGU-lite run as the base and
# enable the robust exploration fixes: length-invariant episodic novelty,
# coarse lifelong keys, soft trust gate, and dual-stream intrinsic advantage.
# Override env vars explicitly for ablations or to reproduce the original run.
# Dataset and algorithm selection intentionally follow the mixed nodynamic base script:
#   DATASET=seta|safety|agentharm|mixed
#   ALGO=grpo|dapo
#
# USAGE:
#   bash terminal-rl/terminal-rl_qwen3-8b_mixed_dapo_nodynamic_exploration_pu.sh
#   DATASET=safety ALGO=dapo bash ...exploration_pu.sh                   # ASB + DAPO override
#   EXPLORATION_PROFILE=robust_dapo_lite bash ...exploration_pu.sh       # conservative DAPO exploration override
#   EXPLORATION_PROFILE=off EXPLORE_AGENT57_LITE=0 bash ...exploration_pu.sh # baseline-style ablation
#   EXPLORE_ENTROPY_COEF=0.01 bash ...exploration_pu.sh                  # +entropy bonus
#   EXPLORE_THINK_MODE=1 bash ...exploration_pu.sh                        # +think mode
#   EXPLORE_INTRINSIC=1 bash ...exploration_pu.sh                         # +intrinsic reward
#   EXPLORE_SAFETY_FILTER=1 bash ...exploration_pu.sh                     # +safety filter
#   ALGO=dapo EXPLORE_CDE_ACTOR=1 bash ...exploration_pu.sh               # +CDE actor/PPL bonus
#   EXPLORE_ENTROPY_COEF=0.01 EXPLORE_INTRINSIC=1 bash ...exploration_pu.sh # combined
#
# BASELINE OPTIONS:
#   DATASET                  : seta|safety|agentharm|mixed (default mixed)
#   ALGO                     : grpo|dapo (default dapo)
#   MIX_SETA_RATIO           : mixed seta ratio
#   MIX_SAFETY_RATIO         : mixed Agent-SafetyBench ratio
#   MIX_AGENTHARM_RATIO      : mixed AgentHarm ratio
#   SETA_SAFETY              : none|clawsentry (default none)
#   SAFETY_BENCH_REWARD      : rule|dense_rule|clawsentry (default dense_rule)
#   AGENTHARM_REWARD         : rule|dense_rule|clawsentry (default dense_rule)
#   TERMINAL_STRUCTURED_METRICS: Emit per-dataset JSON reward breakdowns (default 1)
#   TERMINAL_METRICS_JSONL   : Override JSONL path (default <run_dir>/logs/metrics.jsonl)
#   TERMINAL_WANDB_METRIC_PROFILE: compact|full (default compact)
#
# EXPLORATION OPTIONS:
#   EXPLORATION_PROFILE      : off|robust_dapo_lite|spear_lite (default spear_lite)
#   EXPLORE_ENTROPY_COEF      : Entropy bonus coefficient (default 0.0 = OFF)
#                               Recommended: 0.005 ~ 0.02 (AEPO-style)
#   EXPLORE_THINK_MODE        : Enable Qwen3 think mode (default 1)
#   EXPLORE_TEMP_HIGH         : Rollout temperature override (empty = inherit baseline 1.0)
#   EXPLORE_INTRINSIC         : Count-based intrinsic reward (default 1)
#   EXPLORE_INTRINSIC_COEF    : Intrinsic reward weight (default 0.015)
#   EXPLORE_INTRINSIC_SCHEDULE: constant|cosine|linear (default cosine)
#   EXPLORE_INTRINSIC_DECAY_STEPS: Schedule length in train steps (default 120)
#   EXPLORE_INTRINSIC_GRANULARITY: raw|signature (default signature)
#   EXPLORE_INTRINSIC_SCOPE   : process|episode (default episode)
#   EXPLORE_SAFETY_FILTER     : Regex-based dangerous command penalty (0=OFF, 1=ON)
#   EXPLORE_SAFETY_FILTER_COEF: Safety penalty coefficient (default -0.5)
#   EXPLORE_MAX_TURN          : Override MAX_TURN (empty = inherit baseline 10)
#
# LaMer-inspired Options (from ICLR '26 "Meta-RL Induces Exploration in Language Agents"):
#   EXPLORE_LPRND             : LP-RND lifelong novelty bonus (0=OFF, 1=ON)
#                               Uses mean negative policy logprob as zero-cost novelty
#                               signal; no extra model parameters.
#   EXPLORE_LPRND_COEF        : LP-RND reward weight (default 0.05)
#   EXPLORE_LPRND_SCHEDULE    : constant|cosine|linear (default constant)
#   EXPLORE_LPRND_DECAY_STEPS : Schedule length in train steps (0=OFF)
#   EXPLORE_LPRND_CLIP        : LP-RND z-score clip (default 3.0)
#   EXPLORE_LPRND_WARMUP      : Number of trajectories before LP-RND stats start (default 32)
#   EXPLORE_SCORE_BONUS_COMPONENTS: score-space exploration injection (default none)
#   EXPLORE_ADVANTAGE_BONUS   : Add intrinsic stream after GRPO normalization (default 1)
#   EXPLORE_ADVANTAGE_BONUS_MODE: component|dual_stream (default dual_stream)
#   EXPLORE_ADVANTAGE_LAMBDA  : Dual-stream intrinsic advantage coefficient (default 0.05)
#   EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE: constant|linear|cosine (default constant)
#   EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS: decay horizon for the dual stream (default 0)
#   EXPLORE_ADVANTAGE_BONUS_CLIP: absolute postnorm bonus clip (default 0.5)
#   EXPLORE_CDE_ACTOR         : CDE actor/PPL bonus (default 0)
#                               Adds omega * min(|r|/kappa, alpha * -mean_logprob)
#   EXPLORE_CDE_ACTOR_OMEGA   : CDE actor bonus weight (default 0.02)
#   EXPLORE_CDE_ACTOR_KAPPA   : Reward-magnitude clip divisor (default 4.0)
#   EXPLORE_CDE_ACTOR_ALPHA   : Log-PPL scale before clipping (default 0.05)
#   EXPLORE_CDE_ACTOR_REWARD_GATE: nonzero|positive|none (default positive)
#   EXPLORE_CDE_ACTOR_DECAY_STEPS: Linear omega decay steps (0=OFF)
#   EXPLORE_RETRY_ATTEMPTS    : Multi-attempt reflection (1=OFF/baseline, 2-3=ON)
#                               LaMer uses 3; each failed attempt generates a reflection turn
#   EXPLORE_RETRY_TRAJ_GAMMA  : Cross-attempt discount factor (default 1.0=OFF; LaMer uses 0.6)
#                               Rewards in earlier attempts are discounted, incentivising faster solve

set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Default robust blueprint based on the 2026-06-05 mixed DAPO Agent57/NGU-lite
# run, with think rollout config enabled by default and DAPO dynamic sampling off.
export CUSTOM_CONFIG_PATH=/mnt/shared-storage-user/puyuan/code/OpenClaw-RL/terminal-rl/configs/rollout_qwen3_think.yaml
unset EXPLORE_INTRINSIC_ENABLED EXPLORE_SAFETY_FILTER_ENABLED EXPLORE_LPRND_ENABLED EXPLORE_ADVANTAGE_BONUS_ENABLED EXPLORE_CDE_ACTOR_ENABLED
NUM_GPUS="${NUM_GPUS:-8}"
MIX_MODE="${MIX_MODE:-all_visible}"
SAVE_INTERVAL_SETA="${SAVE_INTERVAL_SETA:-10}"
SAVE_INTERVAL_ASB="${SAVE_INTERVAL_ASB:-10}"
SAVE_INTERVAL_AGENTHARM="${SAVE_INTERVAL_AGENTHARM:-20}"
AVE_INTERVAL_AGENTHARM="${AVE_INTERVAL_AGENTHARM:-${SAVE_INTERVAL_AGENTHARM}}"
MIX_SETA_RATIO="${MIX_SETA_RATIO:-6}"
MIX_SAFETY_RATIO="${MIX_SAFETY_RATIO:-2}"
MIX_AGENTHARM_RATIO="${MIX_AGENTHARM_RATIO:-2}"
ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-4}"
N_SAMPLES="${N_SAMPLES:-8}"
MAX_TURN="${MAX_TURN:-10}"
MAX_CKPT_KEEP="${MAX_CKPT_KEEP:-2}"
TRAJECTORY_SAVE_INTERVAL="${TRAJECTORY_SAVE_INTERVAL:-10}"
TRAJECTORY_SAVE_POLICY="${TRAJECTORY_SAVE_POLICY:-}"
TRAJECTORY_TASK_SAVE_INTERVAL="${TRAJECTORY_TASK_SAVE_INTERVAL:-}"
TRAJECTORY_TASK_MAX_PER_STEP="${TRAJECTORY_TASK_MAX_PER_STEP:-}"
TRAJECTORY_TASK_MAX_PER_TASK="${TRAJECTORY_TASK_MAX_PER_TASK:-}"
TRAJECTORY_MAX_TOTAL="${TRAJECTORY_MAX_TOTAL:-}"
TRAJECTORY_SAVE_REWARD_STRATA="${TRAJECTORY_SAVE_REWARD_STRATA:-}"
TRAJECTORY_SAVE_LOG_DECISIONS="${TRAJECTORY_SAVE_LOG_DECISIONS:-}"
DAPO_DYNAMIC_SAMPLING="${DAPO_DYNAMIC_SAMPLING:-0}"
EXTRA_DAPO_ARGS="${EXTRA_DAPO_ARGS:-}"

# ── Baseline-compatible Dataset / Algorithm Options ─────────────────
# Keep these names/defaults aligned with the mixed nodynamic base script so switching
# between the main and exploration scripts does not require mental translation.
USER_ALGO_SET="${ALGO+x}"
DATASET="${DATASET:-mixed}"
ALGO="${ALGO:-dapo}"
HARNESS_OPTION="${HARNESS_OPTION:-camel-agent}"
case "${DATASET}" in
  seta|safety|agentharm|mixed) ;;
  *)
    echo "[ERROR] Unknown DATASET=${DATASET}. Use: seta|safety|agentharm|mixed" >&2
    exit 1
    ;;
esac
case "${ALGO}" in
  grpo|dapo) ;;
  *)
    echo "[ERROR] Unknown ALGO=${ALGO}. Use: grpo|dapo" >&2
    exit 1
    ;;
esac
case "${HARNESS_OPTION}" in
  camel-agent|camel_agent)
    HARNESS_OPTION="camel-agent"
    ;;
  a3s-code|a3s_code)
    HARNESS_OPTION="a3s-code"
    ;;
  claude-code|claude_code)
    HARNESS_OPTION="claude-code"
    ;;
  *)
    echo "[ERROR] Unknown HARNESS_OPTION=${HARNESS_OPTION}. Use: camel-agent|a3s-code|claude_code" >&2
    exit 1
    ;;
esac
export DATASET ALGO HARNESS_OPTION
RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y-%m-%d_%H%M%S)}"
RUN_ID="${RUN_ID:-terminal-rl_qwen3-8b_${NUM_GPUS}gpu_mixed_dapo_nodynamic_exploration_epi_mean_life_label_decay0.995_ngu_dualadv_think_s${MIX_SETA_RATIO}_asb${MIX_SAFETY_RATIO}_ah${MIX_AGENTHARM_RATIO}_${RUN_TIMESTAMP}}"
RUN_NAME="${RUN_NAME:-${RUN_ID}}"
export NUM_GPUS RUN_TIMESTAMP RUN_ID RUN_NAME
SETA_SAFETY="${SETA_SAFETY:-none}"
SAFETY_BENCH_REWARD="${SAFETY_BENCH_REWARD:-dense_rule}"
AGENTHARM_REWARD="${AGENTHARM_REWARD:-dense_rule}"
SAFETY_REWARD_COEF="${SAFETY_REWARD_COEF:-0}"
export SETA_SAFETY SAFETY_BENCH_REWARD AGENTHARM_REWARD SAFETY_REWARD_COEF

# ── Exploration Options ──
EXPLORATION_PROFILE="${EXPLORATION_PROFILE:-${EXPLORE_PROFILE:-spear_lite}}"
EXPLORE_ENTROPY_COEF="${EXPLORE_ENTROPY_COEF:-0.0}"
EXPLORE_THINK_MODE="${EXPLORE_THINK_MODE:-1}"
EXPLORE_TEMP_HIGH="${EXPLORE_TEMP_HIGH:-}"
EXPLORE_INTRINSIC="${EXPLORE_INTRINSIC:-1}"
EXPLORE_INTRINSIC_COEF="${EXPLORE_INTRINSIC_COEF:-0.015}"
EXPLORE_INTRINSIC_SCHEDULE="${EXPLORE_INTRINSIC_SCHEDULE:-cosine}"
EXPLORE_INTRINSIC_DECAY_STEPS="${EXPLORE_INTRINSIC_DECAY_STEPS:-120}"
EXPLORE_INTRINSIC_REDUCER="${EXPLORE_INTRINSIC_REDUCER:-mean}"
EXPLORE_INTRINSIC_GRANULARITY="${EXPLORE_INTRINSIC_GRANULARITY:-signature}"
EXPLORE_INTRINSIC_SCOPE="${EXPLORE_INTRINSIC_SCOPE:-episode}"
EXPLORE_SCORE_BONUS_COMPONENTS="${EXPLORE_SCORE_BONUS_COMPONENTS:-none}"
EXPLORE_SAFETY_FILTER="${EXPLORE_SAFETY_FILTER:-0}"
EXPLORE_SAFETY_FILTER_COEF="${EXPLORE_SAFETY_FILTER_COEF:--0.5}"
EXPLORE_MAX_TURN="${EXPLORE_MAX_TURN:-}"
# LaMer-inspired
EXPLORE_LPRND="${EXPLORE_LPRND:-0}"
EXPLORE_LPRND_COEF="${EXPLORE_LPRND_COEF:-0.05}"
EXPLORE_LPRND_SCHEDULE="${EXPLORE_LPRND_SCHEDULE:-constant}"
EXPLORE_LPRND_DECAY_STEPS="${EXPLORE_LPRND_DECAY_STEPS:-0}"
EXPLORE_LPRND_CLIP="${EXPLORE_LPRND_CLIP:-3.0}"
EXPLORE_LPRND_WARMUP="${EXPLORE_LPRND_WARMUP:-32}"
# Agent57-lite: K scalar exploration arms + optional run-level lifelong novelty.
EXPLORE_AGENT57_LITE="${EXPLORE_AGENT57_LITE:-1}"
EXPLORE_AGENT57_LITE_ENABLED="${EXPLORE_AGENT57_LITE_ENABLED:-${EXPLORE_AGENT57_LITE}}"
EXPLORE_AGENT57_K="${EXPLORE_AGENT57_K:-8}"
EXPLORE_AGENT57_ARM_BETAS="${EXPLORE_AGENT57_ARM_BETAS:-0,0.002,0.004,0.006,0.008,0.01,0.015,0.02}"
EXPLORE_AGENT57_COMBINE_MODE="${EXPLORE_AGENT57_COMBINE_MODE:-ngu_lite}"
EXPLORE_AGENT57_NGU_MOD_CLIP="${EXPLORE_AGENT57_NGU_MOD_CLIP:-5.0}"
EXPLORE_AGENT57_NGU_EPISODIC_SOURCE="${EXPLORE_AGENT57_NGU_EPISODIC_SOURCE:-signature_intrinsic}"
EXPLORE_AGENT57_NGU_EPISODIC_REDUCER="${EXPLORE_AGENT57_NGU_EPISODIC_REDUCER:-${EXPLORE_INTRINSIC_REDUCER}}"
EXPLORE_AGENT57_NGU_LIFE_MOD_MODE="${EXPLORE_AGENT57_NGU_LIFE_MOD_MODE:-standardized_softplus}"
EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP="${EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP:-5.0}"
EXPLORE_AGENT57_MAX_BONUS="${EXPLORE_AGENT57_MAX_BONUS:-0.05}"
EXPLORE_AGENT57_ARM_TEMPERATURES="${EXPLORE_AGENT57_ARM_TEMPERATURES:-}"
EXPLORE_AGENT57_ARM_TOP_PS="${EXPLORE_AGENT57_ARM_TOP_PS:-}"
EXPLORE_AGENT57_ARM_TOP_KS="${EXPLORE_AGENT57_ARM_TOP_KS:-}"
EXPLORE_AGENT57_CONTROLLER="${EXPLORE_AGENT57_CONTROLLER:-ucb}"
EXPLORE_AGENT57_UCB_C="${EXPLORE_AGENT57_UCB_C:-0.5}"
EXPLORE_AGENT57_UCB_WINDOW="${EXPLORE_AGENT57_UCB_WINDOW:-256}"
EXPLORE_AGENT57_UCB_EPSILON="${EXPLORE_AGENT57_UCB_EPSILON:-0.05}"
EXPLORE_AGENT57_UCB_MIN_PER_ARM="${EXPLORE_AGENT57_UCB_MIN_PER_ARM:-8}"
EXPLORE_AGENT57_UCB_VALUE="${EXPLORE_AGENT57_UCB_VALUE:-normalized_base}"
EXPLORE_AGENT57_UCB_DATASET_AWARE="${EXPLORE_AGENT57_UCB_DATASET_AWARE:-1}"
EXPLORE_AGENT57_UCB_RANDOM_SEED="${EXPLORE_AGENT57_UCB_RANDOM_SEED:-20260605}"
EXPLORE_AGENT57_UCB_SEED_SALT="${EXPLORE_AGENT57_UCB_SEED_SALT:-}"
EXPLORE_AGENT57_KEEP_BASELINE="${EXPLORE_AGENT57_KEEP_BASELINE:-1}"
EPISODIC_MEMORY_BACKEND="${EPISODIC_MEMORY_BACKEND:-simhash_knn}"
EXPLORE_AGENT57_EPISODIC_BACKEND="${EXPLORE_AGENT57_EPISODIC_BACKEND:-${EPISODIC_MEMORY_BACKEND}}"
EXPLORE_AGENT57_EPISODIC_CAPACITY="${EXPLORE_AGENT57_EPISODIC_CAPACITY:-4096}"
EXPLORE_AGENT57_EPISODIC_COUNT_DECAY="${EXPLORE_AGENT57_EPISODIC_COUNT_DECAY:-1.0}"
EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET="${EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET:-1}"
EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS="${EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS:-64}"
EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY="${EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY:-256}"
EXPLORE_AGENT57_EPISODIC_K="${EXPLORE_AGENT57_EPISODIC_K:-5}"
EXPLORE_AGENT57_EPISODIC_DISTANCE="${EXPLORE_AGENT57_EPISODIC_DISTANCE:-cosine}"
EXPLORE_AGENT57_EPISODIC_VECTOR_DIM="${EXPLORE_AGENT57_EPISODIC_VECTOR_DIM:-256}"
EXPLORE_AGENT57_EPISODIC_RANDOM_SEED="${EXPLORE_AGENT57_EPISODIC_RANDOM_SEED:-20260605}"
EXPLORE_AGENT57_EPISODIC_OBS_MODE="${EXPLORE_AGENT57_EPISODIC_OBS_MODE:-fingerprint}"
EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN="${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN:-1}"
EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS="${EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS:-1}"
EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR="${EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR:-0.05}"
EXPLORE_AGENT57_LIFELONG="${EXPLORE_AGENT57_LIFELONG:-1}"
EXPLORE_AGENT57_LIFELONG_ENABLED="${EXPLORE_AGENT57_LIFELONG_ENABLED:-${EXPLORE_AGENT57_LIFELONG}}"
EXPLORE_AGENT57_LIFELONG_COEF="${EXPLORE_AGENT57_LIFELONG_COEF:-0.005}"
EXPLORE_AGENT57_LIFELONG_CLIP="${EXPLORE_AGENT57_LIFELONG_CLIP:-2.0}"
EXPLORE_AGENT57_LIFELONG_WARMUP="${EXPLORE_AGENT57_LIFELONG_WARMUP:-64}"
EXPLORE_AGENT57_LIFELONG_COUNT_DECAY="${EXPLORE_AGENT57_LIFELONG_COUNT_DECAY:-0.995}"
EXPLORE_AGENT57_LIFELONG_CAPACITY="${EXPLORE_AGENT57_LIFELONG_CAPACITY:-200000}"
EXPLORE_AGENT57_LIFELONG_BACKEND="${EXPLORE_AGENT57_LIFELONG_BACKEND:-sqlite}"
EXPLORE_AGENT57_LIFELONG_KEY_VERSION="${EXPLORE_AGENT57_LIFELONG_KEY_VERSION:-v2}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET="${EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET:-1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK:-1}"
EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN="${EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN:-0}"
EXPLORE_AGENT57_LIFELONG_OBS_MODE="${EXPLORE_AGENT57_LIFELONG_OBS_MODE:-fingerprint}"
EXPLORE_AGENT57_LIFELONG_HIERARCHICAL="${EXPLORE_AGENT57_LIFELONG_HIERARCHICAL:-1}"
EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT="${EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT:-0.5}"
EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT="${EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT:-0.35}"
EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT="${EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT:-0.15}"
EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS="${EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS:-30000}"
EXPLORE_AGENT57_SQLITE_WAL="${EXPLORE_AGENT57_SQLITE_WAL:-0}"
EXPLORE_AGENT57_TRUST_GATE="${EXPLORE_AGENT57_TRUST_GATE:-soft}"
EXPLORE_AGENT57_TRUST_COMPLETED="${EXPLORE_AGENT57_TRUST_COMPLETED:-1.0}"
EXPLORE_AGENT57_TRUST_TRUNCATED="${EXPLORE_AGENT57_TRUST_TRUNCATED:-0.3}"
EXPLORE_AGENT57_TRUST_FAILED="${EXPLORE_AGENT57_TRUST_FAILED:-0.1}"
EXPLORE_AGENT57_TRUST_PARSE_ERROR="${EXPLORE_AGENT57_TRUST_PARSE_ERROR:-0.1}"
EXPLORE_AGENT57_TRUST_WARMUP="${EXPLORE_AGENT57_TRUST_WARMUP:-0.3}"
EXPLORE_AGENT57_STATE_PATH="${EXPLORE_AGENT57_STATE_PATH:-}"
EXPLORE_AGENT57_SUCCESS_THRESHOLD="${EXPLORE_AGENT57_SUCCESS_THRESHOLD:-0.0}"
EXPLORE_ADVANTAGE_BONUS="${EXPLORE_ADVANTAGE_BONUS:-1}"
EXPLORE_ADVANTAGE_BONUS_MODE="${EXPLORE_ADVANTAGE_BONUS_MODE:-dual_stream}"
EXPLORE_ADVANTAGE_BONUS_COMPONENTS="${EXPLORE_ADVANTAGE_BONUS_COMPONENTS:-explore_agent57_intrinsic_signal}"
EXPLORE_ADVANTAGE_BONUS_COEF="${EXPLORE_ADVANTAGE_BONUS_COEF:-1.0}"
EXPLORE_ADVANTAGE_BONUS_CLIP="${EXPLORE_ADVANTAGE_BONUS_CLIP:-0.5}"
EXPLORE_ADVANTAGE_INTRINSIC_KEY="${EXPLORE_ADVANTAGE_INTRINSIC_KEY:-explore_agent57_intrinsic_signal}"
EXPLORE_ADVANTAGE_LAMBDA="${EXPLORE_ADVANTAGE_LAMBDA:-0.05}"
EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE="${EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE:-constant}"
EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS="${EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS:-0}"
EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE="${EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE:-normalized_beta}"
EXPLORE_ADVANTAGE_TRUST_KEY="${EXPLORE_ADVANTAGE_TRUST_KEY:-explore_agent57_trust}"
EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE="${EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE:-1.0}"
EXPLORE_ADVANTAGE_FAILED_INTRINSIC_SCALE="${EXPLORE_ADVANTAGE_FAILED_INTRINSIC_SCALE:-1.0}"
EXPLORE_CDE_ACTOR="${EXPLORE_CDE_ACTOR:-0}"
EXPLORE_CDE_ACTOR_OMEGA="${EXPLORE_CDE_ACTOR_OMEGA:-0.02}"
EXPLORE_CDE_ACTOR_KAPPA="${EXPLORE_CDE_ACTOR_KAPPA:-4.0}"
EXPLORE_CDE_ACTOR_ALPHA="${EXPLORE_CDE_ACTOR_ALPHA:-0.05}"
EXPLORE_CDE_ACTOR_DECAY_STEPS="${EXPLORE_CDE_ACTOR_DECAY_STEPS:-0}"
EXPLORE_CDE_ACTOR_REWARD_GATE="${EXPLORE_CDE_ACTOR_REWARD_GATE:-positive}"
EXPLORE_RETRY_ATTEMPTS="${EXPLORE_RETRY_ATTEMPTS:-1}"
EXPLORE_RETRY_TRAJ_GAMMA="${EXPLORE_RETRY_TRAJ_GAMMA:-1.0}"
TERMINAL_STRUCTURED_METRICS="${TERMINAL_STRUCTURED_METRICS:-1}"
TERMINAL_METRICS_JSONL="${TERMINAL_METRICS_JSONL:-}"
TERMINAL_WANDB_METRIC_PROFILE="${TERMINAL_WANDB_METRIC_PROFILE:-compact}"

case "${EXPLORATION_PROFILE}" in
  off|"") ;;
  robust_dapo_lite)
    # Preferred low-risk exploration algorithm:
    # DAPO + small entropy regularization + episode-local signature novelty +
    # dangerous-command penalty. We intentionally keep LP-RND opt-in because it
    # needs more calibration and historically had process-local running stats.
    if [[ -z "${USER_ALGO_SET}" ]]; then
      ALGO="dapo"
      export ALGO
    elif [[ "${ALGO}" != "dapo" ]]; then
      echo "[explore] robust_dapo_lite requires DAPO; overriding ALGO=${ALGO} -> dapo"
      ALGO="dapo"
      export ALGO
    fi
    [[ "${EXPLORE_ENTROPY_COEF}" == "0.0" || "${EXPLORE_ENTROPY_COEF}" == "0" ]] && EXPLORE_ENTROPY_COEF="0.01"
    [[ "${EXPLORE_INTRINSIC}" == "0" ]] && EXPLORE_INTRINSIC="1"
    [[ "${EXPLORE_INTRINSIC_COEF}" == "0.1" ]] && EXPLORE_INTRINSIC_COEF="0.03"
    [[ "${EXPLORE_INTRINSIC_GRANULARITY}" == "raw" ]] && EXPLORE_INTRINSIC_GRANULARITY="signature"
    [[ "${EXPLORE_INTRINSIC_SCOPE}" == "process" ]] && EXPLORE_INTRINSIC_SCOPE="episode"
    [[ "${EXPLORE_SAFETY_FILTER}" == "0" ]] && EXPLORE_SAFETY_FILTER="1"
    ;;
  spear_lite)
    # SPEAR-lite keeps only the low-risk part that fits terminal-rl today:
    # curriculum-scheduled intrinsic tool/command reward. Full SPEAR SIL replay
    # and clip-cov regularization require actor/trainer changes and stay out of
    # this compatibility wrapper.
    if [[ -z "${USER_ALGO_SET}" ]]; then
      ALGO="dapo"
      export ALGO
    elif [[ "${ALGO}" != "dapo" ]]; then
      echo "[explore] spear_lite is calibrated for DAPO; overriding ALGO=${ALGO} -> dapo"
      ALGO="dapo"
      export ALGO
    fi
    [[ "${EXPLORE_INTRINSIC}" == "0" ]] && EXPLORE_INTRINSIC="1"
    [[ "${EXPLORE_INTRINSIC_COEF}" == "0.1" ]] && EXPLORE_INTRINSIC_COEF="0.03"
    [[ "${EXPLORE_INTRINSIC_SCHEDULE}" == "constant" ]] && EXPLORE_INTRINSIC_SCHEDULE="cosine"
    [[ "${EXPLORE_INTRINSIC_DECAY_STEPS}" == "0" ]] && EXPLORE_INTRINSIC_DECAY_STEPS="200"
    [[ "${EXPLORE_INTRINSIC_GRANULARITY}" == "raw" ]] && EXPLORE_INTRINSIC_GRANULARITY="signature"
    [[ "${EXPLORE_INTRINSIC_SCOPE}" == "process" ]] && EXPLORE_INTRINSIC_SCOPE="episode"
    ;;
  *)
    echo "[ERROR] Unknown EXPLORATION_PROFILE=${EXPLORATION_PROFILE}. Use: off|robust_dapo_lite|spear_lite" >&2
    exit 1
    ;;
esac

echo "========================================"
echo "  Exploration Options"
echo "  DATASET         = ${DATASET}"
echo "  ALGO            = ${ALGO}"
echo "  HARNESS_OPTION  = ${HARNESS_OPTION}"
if [[ "${DATASET}" == "mixed" ]]; then
echo "  MIX_RATIOS      = seta:${MIX_SETA_RATIO:-<default>} safety:${MIX_SAFETY_RATIO:-<default>} agentharm:${MIX_AGENTHARM_RATIO:-<unset>}"
fi
echo "  REWARD_MODES    = seta:${SETA_SAFETY} safety:${SAFETY_BENCH_REWARD} agentharm:${AGENTHARM_REWARD} coef:${SAFETY_REWARD_COEF}"
echo "  STRUCTURED_LOGS = ${TERMINAL_STRUCTURED_METRICS} (jsonl=${TERMINAL_METRICS_JSONL:-<run_dir>/logs/metrics.jsonl})"
echo "  WANDB_METRICS   = ${TERMINAL_WANDB_METRIC_PROFILE}"
echo "  TRAJECTORY      = interval:${TRAJECTORY_SAVE_INTERVAL} policy:${TRAJECTORY_SAVE_POLICY:-<base-default>} task_interval:${TRAJECTORY_TASK_SAVE_INTERVAL:-<per-dataset>} per_step:${TRAJECTORY_TASK_MAX_PER_STEP:-<base-default>} per_task:${TRAJECTORY_TASK_MAX_PER_TASK:-<base-default>} max_total:${TRAJECTORY_MAX_TOTAL:-<base-default>} strata:${TRAJECTORY_SAVE_REWARD_STRATA:-<base-default>}"
echo "  PROFILE         = ${EXPLORATION_PROFILE:-off}"
echo "  ENTROPY_COEF    = ${EXPLORE_ENTROPY_COEF}"
echo "  THINK_MODE      = ${EXPLORE_THINK_MODE}"
echo "  TEMP_HIGH       = ${EXPLORE_TEMP_HIGH:-<inherit>}"
echo "  INTRINSIC       = ${EXPLORE_INTRINSIC} (coef=${EXPLORE_INTRINSIC_COEF}, schedule=${EXPLORE_INTRINSIC_SCHEDULE}/${EXPLORE_INTRINSIC_DECAY_STEPS}, reducer=${EXPLORE_INTRINSIC_REDUCER}, granularity=${EXPLORE_INTRINSIC_GRANULARITY}, scope=${EXPLORE_INTRINSIC_SCOPE}, score_components=${EXPLORE_SCORE_BONUS_COMPONENTS})"
echo "  SAFETY_FILTER   = ${EXPLORE_SAFETY_FILTER} (coef=${EXPLORE_SAFETY_FILTER_COEF})"
echo "  MAX_TURN        = ${EXPLORE_MAX_TURN:-<inherit>}"
echo "  LPRND           = ${EXPLORE_LPRND} (coef=${EXPLORE_LPRND_COEF}, schedule=${EXPLORE_LPRND_SCHEDULE}/${EXPLORE_LPRND_DECAY_STEPS}, clip=${EXPLORE_LPRND_CLIP}, warmup=${EXPLORE_LPRND_WARMUP}) [LaMer]"
echo "  AGENT57_LITE    = ${EXPLORE_AGENT57_LITE_ENABLED}/${EXPLORE_AGENT57_LITE} (k=${EXPLORE_AGENT57_K}, controller=${EXPLORE_AGENT57_CONTROLLER}, ucb_eps=${EXPLORE_AGENT57_UCB_EPSILON}, ucb_min=${EXPLORE_AGENT57_UCB_MIN_PER_ARM}, ucb_value=${EXPLORE_AGENT57_UCB_VALUE}, dataset_aware=${EXPLORE_AGENT57_UCB_DATASET_AWARE}, ucb_seed=${EXPLORE_AGENT57_UCB_RANDOM_SEED:-<legacy>}, combine=${EXPLORE_AGENT57_COMBINE_MODE}, ngu_clip=${EXPLORE_AGENT57_NGU_MOD_CLIP}, ngu_reducer=${EXPLORE_AGENT57_NGU_EPISODIC_REDUCER}, life_mod=${EXPLORE_AGENT57_NGU_LIFE_MOD_MODE}/${EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP}, max_bonus=${EXPLORE_AGENT57_MAX_BONUS}, betas=${EXPLORE_AGENT57_ARM_BETAS}, temps=${EXPLORE_AGENT57_ARM_TEMPERATURES:-<inherit>})"
echo "  AGENT57_EPISODE = backend=${EXPLORE_AGENT57_EPISODIC_BACKEND} (capacity=${EXPLORE_AGENT57_EPISODIC_CAPACITY}, decay=${EXPLORE_AGENT57_EPISODIC_COUNT_DECAY}, clear=${EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET}, simhash_bits=${EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS}, bucket=${EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY}, k=${EXPLORE_AGENT57_EPISODIC_K}, distance=${EXPLORE_AGENT57_EPISODIC_DISTANCE}, dim=${EXPLORE_AGENT57_EPISODIC_VECTOR_DIM}, obs=${EXPLORE_AGENT57_EPISODIC_OBS_MODE}, turn=${EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN}, probe=${EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS}, floor=${EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR}, seed=${EXPLORE_AGENT57_EPISODIC_RANDOM_SEED:-<random>})"
echo "  AGENT57_LIFE    = ${EXPLORE_AGENT57_LIFELONG_ENABLED}/${EXPLORE_AGENT57_LIFELONG} (coef=${EXPLORE_AGENT57_LIFELONG_COEF}, clip=${EXPLORE_AGENT57_LIFELONG_CLIP}, warmup=${EXPLORE_AGENT57_LIFELONG_WARMUP}, decay=${EXPLORE_AGENT57_LIFELONG_COUNT_DECAY}, capacity=${EXPLORE_AGENT57_LIFELONG_CAPACITY}, backend=${EXPLORE_AGENT57_LIFELONG_BACKEND}, key=${EXPLORE_AGENT57_LIFELONG_KEY_VERSION}, obs=${EXPLORE_AGENT57_LIFELONG_OBS_MODE}, dataset=${EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET}, task=${EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK}, turn=${EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN}, hierarchical=${EXPLORE_AGENT57_LIFELONG_HIERARCHICAL}, weights=${EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT}/${EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT}/${EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT}, sqlite_timeout_ms=${EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS}, sqlite_wal=${EXPLORE_AGENT57_SQLITE_WAL}, trust=${EXPLORE_AGENT57_TRUST_GATE})"
echo "  POST_NORM_BONUS = ${EXPLORE_ADVANTAGE_BONUS} (mode=${EXPLORE_ADVANTAGE_BONUS_MODE}, components=${EXPLORE_ADVANTAGE_BONUS_COMPONENTS}, coef=${EXPLORE_ADVANTAGE_BONUS_COEF}, lambda=${EXPLORE_ADVANTAGE_LAMBDA}, lambda_schedule=${EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE}/${EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS}, intrinsic_key=${EXPLORE_ADVANTAGE_INTRINSIC_KEY}, arm_weight=${EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE}, trust_key=${EXPLORE_ADVANTAGE_TRUST_KEY}, clip=${EXPLORE_ADVANTAGE_BONUS_CLIP}, trunc_intr_scale=${EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE})"
echo "  CDE_ACTOR       = ${EXPLORE_CDE_ACTOR} (omega=${EXPLORE_CDE_ACTOR_OMEGA}, alpha=${EXPLORE_CDE_ACTOR_ALPHA}, kappa=${EXPLORE_CDE_ACTOR_KAPPA}, gate=${EXPLORE_CDE_ACTOR_REWARD_GATE}, decay_steps=${EXPLORE_CDE_ACTOR_DECAY_STEPS}) [RLVR CDE]"
echo "  RETRY_ATTEMPTS  = ${EXPLORE_RETRY_ATTEMPTS} (traj_gamma=${EXPLORE_RETRY_TRAJ_GAMMA}) [LaMer]"
echo "========================================"

# ── 1. Entropy bonus -> pass to baseline via EXTRA_ALGO_ARGS ──
# Bug fix: the old wrapper used EXTRA_GRPO_ARGS only. The base script
# intentionally ignores EXTRA_GRPO_ARGS when ALGO=dapo, so entropy silently
# disappeared exactly in the DAPO exploration setting this script is meant to run.
# EXTRA_ALGO_ARGS is consumed by both GRPO and DAPO branches.
EXTRA_ALGO_ARGS="${EXTRA_ALGO_ARGS:-}"
if [[ "${EXPLORE_ENTROPY_COEF}" != "0" && "${EXPLORE_ENTROPY_COEF}" != "0.0" ]]; then
  EXTRA_ALGO_ARGS="${EXTRA_ALGO_ARGS} --entropy-coef ${EXPLORE_ENTROPY_COEF}"
  echo "[explore] entropy bonus enabled: ${EXPLORE_ENTROPY_COEF}"
fi
export EXTRA_ALGO_ARGS

# ── 2. Think mode → switch to rollout_qwen3_think.yaml ──
if [[ "${EXPLORE_THINK_MODE}" == "1" ]]; then
  THINK_YAML="${SCRIPT_DIR}/configs/rollout_qwen3_think.yaml"
  if [[ -f "${THINK_YAML}" ]]; then
    export CUSTOM_CONFIG_PATH="${THINK_YAML}"
    echo "[explore] think mode ON: ${THINK_YAML}"
  else
    echo "[WARN] ${THINK_YAML} not found, think mode skipped" >&2
  fi
fi

# ── 3. Temperature override → env var, baseline reads it ──
if [[ -n "${EXPLORE_TEMP_HIGH}" ]]; then
  export ROLLOUT_TEMPERATURE="${EXPLORE_TEMP_HIGH}"
  echo "[explore] rollout temperature overridden to ${EXPLORE_TEMP_HIGH}"
fi

# ── 4. Intrinsic reward → env vars for generate.py ──
if [[ "${EXPLORE_INTRINSIC}" == "1" ]]; then
  export EXPLORE_INTRINSIC_ENABLED="1"
  export EXPLORE_INTRINSIC_COEF
  export EXPLORE_INTRINSIC_SCHEDULE
  export EXPLORE_INTRINSIC_DECAY_STEPS
  export EXPLORE_INTRINSIC_REDUCER
  export EXPLORE_INTRINSIC_GRANULARITY
  export EXPLORE_INTRINSIC_SCOPE
  export EXPLORE_SCORE_BONUS_COMPONENTS
  echo "[explore] intrinsic reward ON (coef=${EXPLORE_INTRINSIC_COEF}, schedule=${EXPLORE_INTRINSIC_SCHEDULE}/${EXPLORE_INTRINSIC_DECAY_STEPS}, reducer=${EXPLORE_INTRINSIC_REDUCER}, score_components=${EXPLORE_SCORE_BONUS_COMPONENTS})"
fi

# ── 5. Safety filter → env vars for generate.py ──
if [[ "${EXPLORE_SAFETY_FILTER}" == "1" ]]; then
  export EXPLORE_SAFETY_FILTER_ENABLED="1"
  export EXPLORE_SAFETY_FILTER_COEF
  echo "[explore] safety pre-filter ON (penalty_coef=${EXPLORE_SAFETY_FILTER_COEF})"
fi

# ── 6. MAX_TURN override ──
if [[ -n "${EXPLORE_MAX_TURN}" ]]; then
  export MAX_TURN="${EXPLORE_MAX_TURN}"
  echo "[explore] MAX_TURN overridden to ${EXPLORE_MAX_TURN}"
fi

# ── 7. LP-RND lifelong novelty (LaMer-inspired) ──
if [[ "${EXPLORE_LPRND}" == "1" ]]; then
  export EXPLORE_LPRND_ENABLED="1"
  export EXPLORE_LPRND_COEF
  export EXPLORE_LPRND_SCHEDULE
  export EXPLORE_LPRND_DECAY_STEPS
  export EXPLORE_LPRND_CLIP
  export EXPLORE_LPRND_WARMUP
  echo "[explore] LP-RND lifelong novelty ON (coef=${EXPLORE_LPRND_COEF}, schedule=${EXPLORE_LPRND_SCHEDULE}/${EXPLORE_LPRND_DECAY_STEPS})"
fi

# ── 8. Optional post-normalization exploration bonus ──
if [[ "${EXPLORE_ADVANTAGE_BONUS}" == "1" ]]; then
  export EXPLORE_ADVANTAGE_BONUS_ENABLED="1"
  export EXPLORE_ADVANTAGE_BONUS_MODE
  export EXPLORE_ADVANTAGE_BONUS_COMPONENTS
  export EXPLORE_ADVANTAGE_BONUS_COEF
  export EXPLORE_ADVANTAGE_BONUS_CLIP
  export EXPLORE_ADVANTAGE_INTRINSIC_KEY
  export EXPLORE_ADVANTAGE_LAMBDA
  export EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE
  export EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS
  export EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE
  export EXPLORE_ADVANTAGE_TRUST_KEY
  export EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE
  export EXPLORE_ADVANTAGE_FAILED_INTRINSIC_SCALE
  echo "[explore] post-normalization bonus ON (mode=${EXPLORE_ADVANTAGE_BONUS_MODE}, lambda=${EXPLORE_ADVANTAGE_LAMBDA}, schedule=${EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE}/${EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS}, intrinsic_key=${EXPLORE_ADVANTAGE_INTRINSIC_KEY}, clip=${EXPLORE_ADVANTAGE_BONUS_CLIP}, trunc_intr_scale=${EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE})"
fi

# ── 9. CDE actor curiosity bonus (RLVR PPL bonus) ──
if [[ "${EXPLORE_CDE_ACTOR}" == "1" ]]; then
  export EXPLORE_CDE_ACTOR_ENABLED="1"
  export EXPLORE_CDE_ACTOR_OMEGA
  export EXPLORE_CDE_ACTOR_KAPPA
  export EXPLORE_CDE_ACTOR_ALPHA
  export EXPLORE_CDE_ACTOR_DECAY_STEPS
  export EXPLORE_CDE_ACTOR_REWARD_GATE
  echo "[explore] CDE actor/PPL bonus ON (omega=${EXPLORE_CDE_ACTOR_OMEGA}, alpha=${EXPLORE_CDE_ACTOR_ALPHA}, kappa=${EXPLORE_CDE_ACTOR_KAPPA}, gate=${EXPLORE_CDE_ACTOR_REWARD_GATE})"
fi

# ── 10. Multi-attempt reflection (LaMer-inspired) ──
if [[ "${EXPLORE_RETRY_ATTEMPTS}" != "1" ]]; then
  export EXPLORE_RETRY_ATTEMPTS
  export EXPLORE_RETRY_TRAJ_GAMMA
  echo "[explore] multi-attempt reflection ON (attempts=${EXPLORE_RETRY_ATTEMPTS}, traj_gamma=${EXPLORE_RETRY_TRAJ_GAMMA})"
  echo "[WARN] Multi-attempt requires agent_runner support (not yet implemented in terminal-rl)" >&2
fi

# ── 11. Build RUN_ID suffix for easy identification ──
SUF=""
[[ "${EXPLORATION_PROFILE:-off}" != "off" && -n "${EXPLORATION_PROFILE:-}" ]] && SUF="${SUF}_${EXPLORATION_PROFILE}"
[[ "${EXPLORE_ENTROPY_COEF}" != "0" && "${EXPLORE_ENTROPY_COEF}" != "0.0" ]] && SUF="${SUF}_ent${EXPLORE_ENTROPY_COEF}"
[[ "${EXPLORE_THINK_MODE}" == "1" ]] && SUF="${SUF}_think"
[[ -n "${EXPLORE_TEMP_HIGH}" ]] && SUF="${SUF}_T${EXPLORE_TEMP_HIGH}"
[[ "${EXPLORE_INTRINSIC}" == "1" ]] && SUF="${SUF}_int"
[[ "${EXPLORE_INTRINSIC}" == "1" && "${EXPLORE_INTRINSIC_SCHEDULE}" != "constant" ]] && SUF="${SUF}_${EXPLORE_INTRINSIC_SCHEDULE}${EXPLORE_INTRINSIC_DECAY_STEPS}"
[[ "${EXPLORE_SAFETY_FILTER}" == "1" ]] && SUF="${SUF}_safe"
[[ "${EXPLORE_LPRND}" == "1" ]] && SUF="${SUF}_lprnd"
[[ "${EXPLORE_LPRND}" == "1" && "${EXPLORE_LPRND_SCHEDULE}" != "constant" ]] && SUF="${SUF}_${EXPLORE_LPRND_SCHEDULE}${EXPLORE_LPRND_DECAY_STEPS}"
[[ "${EXPLORE_AGENT57_LITE_ENABLED}" == "1" || "${EXPLORE_AGENT57_LITE}" == "1" ]] && SUF="${SUF}_a57"
[[ "${EXPLORE_AGENT57_LIFELONG_ENABLED}" == "1" || "${EXPLORE_AGENT57_LIFELONG}" == "1" ]] && SUF="${SUF}_life${EXPLORE_AGENT57_LIFELONG_COEF}"
[[ "${EXPLORE_ADVANTAGE_BONUS}" == "1" ]] && SUF="${SUF}_postnorm"
[[ "${EXPLORE_CDE_ACTOR}" == "1" ]] && SUF="${SUF}_cdeact${EXPLORE_CDE_ACTOR_OMEGA}"
[[ "${EXPLORE_RETRY_ATTEMPTS}" != "1" ]] && SUF="${SUF}_retry${EXPLORE_RETRY_ATTEMPTS}"

if [[ -n "${SUF}" ]]; then
  TS="${RUN_TIMESTAMP:-$(date +%F_%H%M%S)}"
  if command -v nvidia-smi >/dev/null 2>&1; then
    GPUS="$(nvidia-smi -L 2>/dev/null | wc -l || echo 0)"
  else
    GPUS=0
  fi
  if [[ "${GPUS}" -le 0 ]]; then
    GPUS="${NUM_GPUS:-4}"
  fi
  export RUN_TIMESTAMP="${TS}"
  RUN_HARNESS_TAG="$(printf '%s' "${HARNESS_OPTION}" | tr -c 'A-Za-z0-9_.-' '-' | sed 's/-\{1,\}/-/g; s/^-//; s/-$//')"
  export RUN_ID="${RUN_ID:-terminal-rl_qwen3-8b_${GPUS}gpu_${DATASET}_${ALGO}_harness-${RUN_HARNESS_TAG}_explore${SUF}_${TS}}"
  echo "[explore] RUN_ID=${RUN_ID}"
fi

# Export all knobs so the main script can persist them in run_config and forward
# them to Ray runtime_env. Without this, generate.py workers do not reliably see
# exploration settings under ray job submit.
export CUSTOM_CONFIG_PATH
export MIX_MODE SAVE_INTERVAL_SETA SAVE_INTERVAL_ASB SAVE_INTERVAL_AGENTHARM AVE_INTERVAL_AGENTHARM
export MIX_SETA_RATIO MIX_SAFETY_RATIO MIX_AGENTHARM_RATIO
export ROLLOUT_BATCH_SIZE N_SAMPLES MAX_TURN MAX_CKPT_KEEP TRAJECTORY_SAVE_INTERVAL DAPO_DYNAMIC_SAMPLING EXTRA_DAPO_ARGS
export TRAJECTORY_SAVE_POLICY TRAJECTORY_TASK_SAVE_INTERVAL TRAJECTORY_TASK_MAX_PER_STEP
export TRAJECTORY_TASK_MAX_PER_TASK TRAJECTORY_MAX_TOTAL TRAJECTORY_SAVE_REWARD_STRATA
export TRAJECTORY_SAVE_LOG_DECISIONS
export EXPLORATION_PROFILE
export EXPLORE_ENTROPY_COEF EXPLORE_THINK_MODE EXPLORE_TEMP_HIGH
export EXPLORE_INTRINSIC EXPLORE_INTRINSIC_COEF EXPLORE_INTRINSIC_SCHEDULE EXPLORE_INTRINSIC_DECAY_STEPS EXPLORE_INTRINSIC_REDUCER EXPLORE_INTRINSIC_GRANULARITY EXPLORE_INTRINSIC_SCOPE EXPLORE_SCORE_BONUS_COMPONENTS
export EXPLORE_SAFETY_FILTER EXPLORE_SAFETY_FILTER_COEF
export EXPLORE_MAX_TURN EXPLORE_LPRND EXPLORE_LPRND_COEF EXPLORE_LPRND_SCHEDULE EXPLORE_LPRND_DECAY_STEPS EXPLORE_LPRND_CLIP EXPLORE_LPRND_WARMUP
export EXPLORE_AGENT57_LITE EXPLORE_AGENT57_LITE_ENABLED EXPLORE_AGENT57_K EXPLORE_AGENT57_ARM_BETAS EXPLORE_AGENT57_COMBINE_MODE EXPLORE_AGENT57_NGU_MOD_CLIP EXPLORE_AGENT57_NGU_EPISODIC_SOURCE EXPLORE_AGENT57_NGU_EPISODIC_REDUCER EXPLORE_AGENT57_NGU_LIFE_MOD_MODE EXPLORE_AGENT57_NGU_LIFE_MOD_STD_CLIP EXPLORE_AGENT57_MAX_BONUS EXPLORE_AGENT57_ARM_TEMPERATURES EXPLORE_AGENT57_ARM_TOP_PS EXPLORE_AGENT57_ARM_TOP_KS
export EXPLORE_AGENT57_CONTROLLER EXPLORE_AGENT57_UCB_C EXPLORE_AGENT57_UCB_WINDOW EXPLORE_AGENT57_UCB_EPSILON EXPLORE_AGENT57_UCB_MIN_PER_ARM EXPLORE_AGENT57_UCB_VALUE EXPLORE_AGENT57_UCB_DATASET_AWARE EXPLORE_AGENT57_UCB_RANDOM_SEED EXPLORE_AGENT57_UCB_SEED_SALT EXPLORE_AGENT57_KEEP_BASELINE
export EPISODIC_MEMORY_BACKEND EXPLORE_AGENT57_EPISODIC_BACKEND EXPLORE_AGENT57_EPISODIC_CAPACITY EXPLORE_AGENT57_EPISODIC_COUNT_DECAY EXPLORE_AGENT57_EPISODIC_CLEAR_ON_RESET EXPLORE_AGENT57_EPISODIC_SIMHASH_BITS EXPLORE_AGENT57_EPISODIC_BUCKET_CAPACITY EXPLORE_AGENT57_EPISODIC_K EXPLORE_AGENT57_EPISODIC_DISTANCE EXPLORE_AGENT57_EPISODIC_VECTOR_DIM EXPLORE_AGENT57_EPISODIC_RANDOM_SEED EXPLORE_AGENT57_EPISODIC_OBS_MODE EXPLORE_AGENT57_EPISODIC_INCLUDE_TURN EXPLORE_AGENT57_EPISODIC_MULTI_PROBE_RADIUS EXPLORE_AGENT57_EPISODIC_NOVELTY_FLOOR
export EXPLORE_AGENT57_LIFELONG EXPLORE_AGENT57_LIFELONG_ENABLED EXPLORE_AGENT57_LIFELONG_COEF EXPLORE_AGENT57_LIFELONG_CLIP EXPLORE_AGENT57_LIFELONG_WARMUP EXPLORE_AGENT57_LIFELONG_COUNT_DECAY EXPLORE_AGENT57_LIFELONG_CAPACITY EXPLORE_AGENT57_LIFELONG_BACKEND EXPLORE_AGENT57_LIFELONG_KEY_VERSION EXPLORE_AGENT57_LIFELONG_INCLUDE_DATASET EXPLORE_AGENT57_LIFELONG_INCLUDE_TASK EXPLORE_AGENT57_LIFELONG_INCLUDE_TURN EXPLORE_AGENT57_LIFELONG_OBS_MODE EXPLORE_AGENT57_LIFELONG_HIERARCHICAL EXPLORE_AGENT57_LIFELONG_TASK_WEIGHT EXPLORE_AGENT57_LIFELONG_SKILL_WEIGHT EXPLORE_AGENT57_LIFELONG_GLOBAL_WEIGHT EXPLORE_AGENT57_SQLITE_BUSY_TIMEOUT_MS EXPLORE_AGENT57_SQLITE_WAL EXPLORE_AGENT57_TRUST_GATE EXPLORE_AGENT57_TRUST_COMPLETED EXPLORE_AGENT57_TRUST_TRUNCATED EXPLORE_AGENT57_TRUST_FAILED EXPLORE_AGENT57_TRUST_PARSE_ERROR EXPLORE_AGENT57_TRUST_WARMUP EXPLORE_AGENT57_STATE_PATH EXPLORE_AGENT57_SUCCESS_THRESHOLD
export EXPLORE_ADVANTAGE_BONUS EXPLORE_ADVANTAGE_BONUS_MODE EXPLORE_ADVANTAGE_BONUS_COMPONENTS EXPLORE_ADVANTAGE_BONUS_COEF EXPLORE_ADVANTAGE_BONUS_CLIP EXPLORE_ADVANTAGE_INTRINSIC_KEY EXPLORE_ADVANTAGE_LAMBDA EXPLORE_ADVANTAGE_LAMBDA_SCHEDULE EXPLORE_ADVANTAGE_LAMBDA_DECAY_STEPS EXPLORE_ADVANTAGE_ARM_WEIGHT_MODE EXPLORE_ADVANTAGE_TRUST_KEY EXPLORE_ADVANTAGE_TRUNCATED_INTRINSIC_SCALE EXPLORE_ADVANTAGE_FAILED_INTRINSIC_SCALE
export EXPLORE_CDE_ACTOR EXPLORE_CDE_ACTOR_OMEGA EXPLORE_CDE_ACTOR_KAPPA EXPLORE_CDE_ACTOR_ALPHA EXPLORE_CDE_ACTOR_DECAY_STEPS EXPLORE_CDE_ACTOR_REWARD_GATE
export EXPLORE_RETRY_ATTEMPTS EXPLORE_RETRY_TRAJ_GAMMA
export TERMINAL_STRUCTURED_METRICS TERMINAL_METRICS_JSONL TERMINAL_WANDB_METRIC_PROFILE

# ── 12. Execute mixed nodynamic baseline script ──
exec bash "${SCRIPT_DIR}/terminal-rl_qwen3-8b_mixed_dapo_nodynamic_pu.sh" "$@"
