#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd)"

DEFAULT_A3S_CODE_PYTHON_BIN="python3"
if [[ -n "${CONDA_PREFIX:-}" && -x "${CONDA_PREFIX}/bin/python3" ]]; then
  DEFAULT_A3S_CODE_PYTHON_BIN="${CONDA_PREFIX}/bin/python3"
elif [[ -n "${CONDA_ENV:-}" && -x "${CONDA_ENV}/bin/python3" ]]; then
  DEFAULT_A3S_CODE_PYTHON_BIN="${CONDA_ENV}/bin/python3"
fi

export RL_BASE_URL="${RL_BASE_URL:-http://127.0.0.1:30000}"
export KIMI_BASE_URL="${KIMI_BASE_URL:-http://s-20260204175507-cqflp.ailab-pj.pjh-service.org.cn}"
export SIMULATED_USER_BASE_URL="${SIMULATED_USER_BASE_URL:-${KIMI_BASE_URL}}"
export SIMULATED_USER_MODEL_URL="${SIMULATED_USER_MODEL_URL:-${SIMULATED_USER_BASE_URL}/v1/chat/completions}"
export SIMULATED_USER_MODEL_NAME="${SIMULATED_USER_MODEL_NAME:-kimi-k2.5}"
export SIMULATED_USER_API_KEY="${SIMULATED_USER_API_KEY:-}"
export SIMULATED_USER_MODEL_URLS="${SIMULATED_USER_MODEL_URLS:-${SIMULATED_USER_MODEL_URL}}"
export SIMULATED_USER_MODEL_NAMES="${SIMULATED_USER_MODEL_NAMES:-${SIMULATED_USER_MODEL_NAME}}"
export SIMULATED_USER_API_KEYS="${SIMULATED_USER_API_KEYS:-${SIMULATED_USER_API_KEY}}"
export A3S_MODEL_NAME="${A3S_MODEL_NAME:-qwen3-4b}"
export A3S_API_KEY="${A3S_API_KEY:-${SGLANG_API_KEY:-apiKey}}"
export A3S_CODE_PYTHON_BIN="${A3S_CODE_PYTHON_BIN:-${DEFAULT_A3S_CODE_PYTHON_BIN}}"
export A3S_CODE_REPO_ROOT="${A3S_CODE_REPO_ROOT:-$(cd -- "${PROJECT_ROOT}/../a3s-lab/Code" 2>/dev/null && pwd || echo "${PROJECT_ROOT}/a3s-lab/Code")}"
export A3S_CODE_EXTRA_SITE_PACKAGES="${A3S_CODE_EXTRA_SITE_PACKAGES:-}"
export A3S_CODE_TRAFFIC_CONCURRENCY="${A3S_CODE_TRAFFIC_CONCURRENCY:-1}"
export A3S_CODE_TRAFFIC_SESSION_LIMIT="${A3S_CODE_TRAFFIC_SESSION_LIMIT:-0}"
export A3S_CODE_MAX_MAIN_TURNS="${A3S_CODE_MAX_MAIN_TURNS:-4}"
export A3S_CODE_MAX_TOOL_ROUNDS="${A3S_CODE_MAX_TOOL_ROUNDS:-16}"
export A3S_CODE_TOOL_TIMEOUT_MS="${A3S_CODE_TOOL_TIMEOUT_MS:-300000}"
export A3S_CODE_MAX_PARSE_RETRIES="${A3S_CODE_MAX_PARSE_RETRIES:-4}"
export A3S_CODE_CIRCUIT_BREAKER_THRESHOLD="${A3S_CODE_CIRCUIT_BREAKER_THRESHOLD:-5}"
export A3S_CODE_SIMULATED_USER_TIMEOUT_SEC="${A3S_CODE_SIMULATED_USER_TIMEOUT_SEC:-45}"
export A3S_CODE_SIMULATED_USER_BACKEND_COOLDOWN_SEC="${A3S_CODE_SIMULATED_USER_BACKEND_COOLDOWN_SEC:-60}"
export A3S_CODE_SIMULATED_USER_MAX_ATTEMPTS="${A3S_CODE_SIMULATED_USER_MAX_ATTEMPTS:-0}"
export A3S_CODE_REQUEST_TIMEOUT_SEC="${A3S_CODE_REQUEST_TIMEOUT_SEC:-900}"
export A3S_CODE_TURN_TIMEOUT_SEC="${A3S_CODE_TURN_TIMEOUT_SEC:-600}"
export A3S_CODE_SESSION_DELAY_SEC="${A3S_CODE_SESSION_DELAY_SEC:-1}"
export A3S_CODE_KEEP_WORKSPACES="${A3S_CODE_KEEP_WORKSPACES:-0}"
export A3S_CODE_KEEP_WORKSPACES_ON_ERROR="${A3S_CODE_KEEP_WORKSPACES_ON_ERROR:-0}"
export A3S_CODE_KEEP_CONFIGS="${A3S_CODE_KEEP_CONFIGS:-0}"
export A3S_CODE_AGENT_CONFIG_MODE="${A3S_CODE_AGENT_CONFIG_MODE:-shared}"
export A3S_CODE_SESSION_ID_HEADER_NAME="${A3S_CODE_SESSION_ID_HEADER_NAME:-X-Session-Id}"
export A3S_CODE_WORKSPACE_COPY_MODE="${A3S_CODE_WORKSPACE_COPY_MODE:-reflink_auto}"
export CODE_RL_MATCHED_CONTEXT_TOKENS="${CODE_RL_MATCHED_CONTEXT_TOKENS:-8192}"
export A3S_CODE_CONTEXT_HEADROOM_TOKENS="${A3S_CODE_CONTEXT_HEADROOM_TOKENS:-1024}"
default_a3s_context_tokens=$((CODE_RL_MATCHED_CONTEXT_TOKENS - A3S_CODE_CONTEXT_HEADROOM_TOKENS))
if (( default_a3s_context_tokens < 1024 )); then
  default_a3s_context_tokens=1024
fi
export A3S_CODE_MODEL_CONTEXT_TOKENS="${A3S_CODE_MODEL_CONTEXT_TOKENS:-${default_a3s_context_tokens}}"
export A3S_CODE_MODEL_OUTPUT_TOKENS="${A3S_CODE_MODEL_OUTPUT_TOKENS:-2048}"
export A3S_CODE_THINKING_BUDGET="${A3S_CODE_THINKING_BUDGET:-16000}"
export A3S_CODE_AUTO_COMPACT="${A3S_CODE_AUTO_COMPACT:-1}"
export A3S_CODE_AUTO_COMPACT_THRESHOLD="${A3S_CODE_AUTO_COMPACT_THRESHOLD:-0.7}"
export A3S_CODE_CONTINUATION_ENABLED="${A3S_CODE_CONTINUATION_ENABLED:-0}"
export A3S_CODE_MAX_CONTINUATION_TURNS="${A3S_CODE_MAX_CONTINUATION_TURNS:-5}"
export A3S_CODE_GIT_USER_NAME="${A3S_CODE_GIT_USER_NAME:-A3S Code RL}"
export A3S_CODE_GIT_USER_EMAIL="${A3S_CODE_GIT_USER_EMAIL:-a3s-code-rl@example.com}"
export A3S_CODE_WORKSPACE_ROOT="${A3S_CODE_WORKSPACE_ROOT:-${SCRIPT_DIR}/generated_workspaces}"
export A3S_CODE_CONFIG_ROOT="${A3S_CODE_CONFIG_ROOT:-${SCRIPT_DIR}/generated_configs}"
export A3S_CODE_WORKSPACE_TEMPLATE_CACHE_ROOT="${A3S_CODE_WORKSPACE_TEMPLATE_CACHE_ROOT:-${SCRIPT_DIR}/workspace_template_cache}"
export A3S_CODE_SIMULATED_USER_BACKENDS_FILE="${A3S_CODE_SIMULATED_USER_BACKENDS_FILE:-${SCRIPT_DIR}/simulated_user_backends.json}"
export A3S_CODE_SIMULATED_USER_PROBE_TIMEOUT_SEC="${A3S_CODE_SIMULATED_USER_PROBE_TIMEOUT_SEC:-20}"
export A3S_CODE_REFRESH_SIMULATED_USER_BACKENDS_ON_START="${A3S_CODE_REFRESH_SIMULATED_USER_BACKENDS_ON_START:-1}"
export A3S_CODE_GIT_CONFIG_GLOBAL="${A3S_CODE_GIT_CONFIG_GLOBAL:-${A3S_CODE_CONFIG_ROOT}/git-global-$$.cfg}"
export A3S_CODE_CLEANUP_ON_START="${A3S_CODE_CLEANUP_ON_START:-0}"
export A3S_CODE_GENERATED_TTL_HOURS="${A3S_CODE_GENERATED_TTL_HOURS:-12}"

mkdir -p "${A3S_CODE_CONFIG_ROOT}"
: > "${A3S_CODE_GIT_CONFIG_GLOBAL}"
export GIT_CONFIG_GLOBAL="${GIT_CONFIG_GLOBAL:-${A3S_CODE_GIT_CONFIG_GLOBAL}}"

if [[ "${A3S_CODE_CLEANUP_ON_START}" == "1" && "${A3S_CODE_GENERATED_TTL_HOURS}" != "0" ]]; then
  ttl_minutes="$((A3S_CODE_GENERATED_TTL_HOURS * 60))"
  mkdir -p "${A3S_CODE_WORKSPACE_ROOT}" "${A3S_CODE_CONFIG_ROOT}"
  find "${A3S_CODE_WORKSPACE_ROOT}" -mindepth 1 -maxdepth 1 -mmin "+${ttl_minutes}" -exec rm -rf {} + 2>/dev/null || true
  find "${A3S_CODE_CONFIG_ROOT}" -mindepth 1 -maxdepth 1 -mmin "+${ttl_minutes}" -delete 2>/dev/null || true
fi

if [[ "${A3S_CODE_REFRESH_SIMULATED_USER_BACKENDS_ON_START}" == "1" ]]; then
  bash "${SCRIPT_DIR}/refresh_simulated_user_backends.sh"
fi

"${A3S_CODE_PYTHON_BIN}" -u "${SCRIPT_DIR}/a3s_code_agent_traffic_driver.py"
